//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.4927.
// 
#pragma warning disable 1591

namespace umsalertix.alertix.admin {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AdminApiHttpBinding", Namespace="http://api.alertix.cellvision")]
    public partial class AdminApi : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getWhiteListSubscribersOperationCompleted;
        
        private System.Threading.SendOrPostCallback getWhiteListsOperationCompleted;
        
        private System.Threading.SendOrPostCallback createWhiteListOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteWhiteListOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteWhiteListSubscribersOperationCompleted;
        
        private System.Threading.SendOrPostCallback addWhiteListSubscribersOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AdminApi() {
            this.Url = global::umsalertix.Properties.Settings.Default.umsalertix_alertix_admin_AdminApi;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getWhiteListSubscribersCompletedEventHandler getWhiteListSubscribersCompleted;
        
        /// <remarks/>
        public event getWhiteListsCompletedEventHandler getWhiteListsCompleted;
        
        /// <remarks/>
        public event createWhiteListCompletedEventHandler createWhiteListCompleted;
        
        /// <remarks/>
        public event deleteWhiteListCompletedEventHandler deleteWhiteListCompleted;
        
        /// <remarks/>
        public event deleteWhiteListSubscribersCompletedEventHandler deleteWhiteListSubscribersCompleted;
        
        /// <remarks/>
        public event addWhiteListSubscribersCompletedEventHandler addWhiteListSubscribersCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://api.alertix.cellvision", ResponseNamespace="http://api.alertix.cellvision", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public SubscribersResponse getWhiteListSubscribers([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] WhiteListName in0) {
            object[] results = this.Invoke("getWhiteListSubscribers", new object[] {
                        in0});
            return ((SubscribersResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getWhiteListSubscribersAsync(WhiteListName in0) {
            this.getWhiteListSubscribersAsync(in0, null);
        }
        
        /// <remarks/>
        public void getWhiteListSubscribersAsync(WhiteListName in0, object userState) {
            if ((this.getWhiteListSubscribersOperationCompleted == null)) {
                this.getWhiteListSubscribersOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetWhiteListSubscribersOperationCompleted);
            }
            this.InvokeAsync("getWhiteListSubscribers", new object[] {
                        in0}, this.getWhiteListSubscribersOperationCompleted, userState);
        }
        
        private void OngetWhiteListSubscribersOperationCompleted(object arg) {
            if ((this.getWhiteListSubscribersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getWhiteListSubscribersCompleted(this, new getWhiteListSubscribersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://api.alertix.cellvision", ResponseNamespace="http://api.alertix.cellvision", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public WhiteListsResponse getWhiteLists() {
            object[] results = this.Invoke("getWhiteLists", new object[0]);
            return ((WhiteListsResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getWhiteListsAsync() {
            this.getWhiteListsAsync(null);
        }
        
        /// <remarks/>
        public void getWhiteListsAsync(object userState) {
            if ((this.getWhiteListsOperationCompleted == null)) {
                this.getWhiteListsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetWhiteListsOperationCompleted);
            }
            this.InvokeAsync("getWhiteLists", new object[0], this.getWhiteListsOperationCompleted, userState);
        }
        
        private void OngetWhiteListsOperationCompleted(object arg) {
            if ((this.getWhiteListsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getWhiteListsCompleted(this, new getWhiteListsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://api.alertix.cellvision", ResponseNamespace="http://api.alertix.cellvision", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public Response createWhiteList([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] WhiteListName in0) {
            object[] results = this.Invoke("createWhiteList", new object[] {
                        in0});
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public void createWhiteListAsync(WhiteListName in0) {
            this.createWhiteListAsync(in0, null);
        }
        
        /// <remarks/>
        public void createWhiteListAsync(WhiteListName in0, object userState) {
            if ((this.createWhiteListOperationCompleted == null)) {
                this.createWhiteListOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateWhiteListOperationCompleted);
            }
            this.InvokeAsync("createWhiteList", new object[] {
                        in0}, this.createWhiteListOperationCompleted, userState);
        }
        
        private void OncreateWhiteListOperationCompleted(object arg) {
            if ((this.createWhiteListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.createWhiteListCompleted(this, new createWhiteListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://api.alertix.cellvision", ResponseNamespace="http://api.alertix.cellvision", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public Response deleteWhiteList([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] WhiteListName in0) {
            object[] results = this.Invoke("deleteWhiteList", new object[] {
                        in0});
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public void deleteWhiteListAsync(WhiteListName in0) {
            this.deleteWhiteListAsync(in0, null);
        }
        
        /// <remarks/>
        public void deleteWhiteListAsync(WhiteListName in0, object userState) {
            if ((this.deleteWhiteListOperationCompleted == null)) {
                this.deleteWhiteListOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteWhiteListOperationCompleted);
            }
            this.InvokeAsync("deleteWhiteList", new object[] {
                        in0}, this.deleteWhiteListOperationCompleted, userState);
        }
        
        private void OndeleteWhiteListOperationCompleted(object arg) {
            if ((this.deleteWhiteListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteWhiteListCompleted(this, new deleteWhiteListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://api.alertix.cellvision", ResponseNamespace="http://api.alertix.cellvision", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public DeleteResponse deleteWhiteListSubscribers([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] WhiteListName in0, [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://api.domain.common.alertix.cellvision")] Msisdn[] in1) {
            object[] results = this.Invoke("deleteWhiteListSubscribers", new object[] {
                        in0,
                        in1});
            return ((DeleteResponse)(results[0]));
        }
        
        /// <remarks/>
        public void deleteWhiteListSubscribersAsync(WhiteListName in0, Msisdn[] in1) {
            this.deleteWhiteListSubscribersAsync(in0, in1, null);
        }
        
        /// <remarks/>
        public void deleteWhiteListSubscribersAsync(WhiteListName in0, Msisdn[] in1, object userState) {
            if ((this.deleteWhiteListSubscribersOperationCompleted == null)) {
                this.deleteWhiteListSubscribersOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteWhiteListSubscribersOperationCompleted);
            }
            this.InvokeAsync("deleteWhiteListSubscribers", new object[] {
                        in0,
                        in1}, this.deleteWhiteListSubscribersOperationCompleted, userState);
        }
        
        private void OndeleteWhiteListSubscribersOperationCompleted(object arg) {
            if ((this.deleteWhiteListSubscribersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteWhiteListSubscribersCompleted(this, new deleteWhiteListSubscribersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://api.alertix.cellvision", ResponseNamespace="http://api.alertix.cellvision", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public AddResponse addWhiteListSubscribers([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] WhiteListName in0, [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://api.domain.common.alertix.cellvision")] Msisdn[] in1) {
            object[] results = this.Invoke("addWhiteListSubscribers", new object[] {
                        in0,
                        in1});
            return ((AddResponse)(results[0]));
        }
        
        /// <remarks/>
        public void addWhiteListSubscribersAsync(WhiteListName in0, Msisdn[] in1) {
            this.addWhiteListSubscribersAsync(in0, in1, null);
        }
        
        /// <remarks/>
        public void addWhiteListSubscribersAsync(WhiteListName in0, Msisdn[] in1, object userState) {
            if ((this.addWhiteListSubscribersOperationCompleted == null)) {
                this.addWhiteListSubscribersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddWhiteListSubscribersOperationCompleted);
            }
            this.InvokeAsync("addWhiteListSubscribers", new object[] {
                        in0,
                        in1}, this.addWhiteListSubscribersOperationCompleted, userState);
        }
        
        private void OnaddWhiteListSubscribersOperationCompleted(object arg) {
            if ((this.addWhiteListSubscribersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addWhiteListSubscribersCompleted(this, new addWhiteListSubscribersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.domain.common.alertix.cellvision")]
    public partial class WhiteListName {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://vo.api.alertix.cellvision")]
    public partial class AddResponse {
        
        private int addedCountField;
        
        private bool addedCountFieldSpecified;
        
        private int codeField;
        
        private bool codeFieldSpecified;
        
        private string messageField;
        
        private bool successfulField;
        
        private bool successfulFieldSpecified;
        
        /// <remarks/>
        public int addedCount {
            get {
                return this.addedCountField;
            }
            set {
                this.addedCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool addedCountSpecified {
            get {
                return this.addedCountFieldSpecified;
            }
            set {
                this.addedCountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codeSpecified {
            get {
                return this.codeFieldSpecified;
            }
            set {
                this.codeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public bool successful {
            get {
                return this.successfulField;
            }
            set {
                this.successfulField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool successfulSpecified {
            get {
                return this.successfulFieldSpecified;
            }
            set {
                this.successfulFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://vo.api.alertix.cellvision")]
    public partial class DeleteResponse {
        
        private int codeField;
        
        private bool codeFieldSpecified;
        
        private int deletedCountField;
        
        private bool deletedCountFieldSpecified;
        
        private string messageField;
        
        private bool successfulField;
        
        private bool successfulFieldSpecified;
        
        /// <remarks/>
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codeSpecified {
            get {
                return this.codeFieldSpecified;
            }
            set {
                this.codeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int deletedCount {
            get {
                return this.deletedCountField;
            }
            set {
                this.deletedCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool deletedCountSpecified {
            get {
                return this.deletedCountFieldSpecified;
            }
            set {
                this.deletedCountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public bool successful {
            get {
                return this.successfulField;
            }
            set {
                this.successfulField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool successfulSpecified {
            get {
                return this.successfulFieldSpecified;
            }
            set {
                this.successfulFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://vo.common.alertix.cellvision")]
    public partial class Response {
        
        private int codeField;
        
        private bool codeFieldSpecified;
        
        private string messageField;
        
        private bool successfulField;
        
        private bool successfulFieldSpecified;
        
        /// <remarks/>
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codeSpecified {
            get {
                return this.codeFieldSpecified;
            }
            set {
                this.codeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public bool successful {
            get {
                return this.successfulField;
            }
            set {
                this.successfulField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool successfulSpecified {
            get {
                return this.successfulFieldSpecified;
            }
            set {
                this.successfulFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://vo.api.alertix.cellvision")]
    public partial class WhiteListsResponse {
        
        private int codeField;
        
        private bool codeFieldSpecified;
        
        private string messageField;
        
        private bool successfulField;
        
        private bool successfulFieldSpecified;
        
        private WhiteListName[] whiteListsField;
        
        /// <remarks/>
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codeSpecified {
            get {
                return this.codeFieldSpecified;
            }
            set {
                this.codeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public bool successful {
            get {
                return this.successfulField;
            }
            set {
                this.successfulField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool successfulSpecified {
            get {
                return this.successfulFieldSpecified;
            }
            set {
                this.successfulFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://api.domain.common.alertix.cellvision")]
        public WhiteListName[] whiteLists {
            get {
                return this.whiteListsField;
            }
            set {
                this.whiteListsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.domain.common.alertix.cellvision")]
    public partial class Msisdn {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://vo.api.alertix.cellvision")]
    public partial class SubscribersResponse {
        
        private int codeField;
        
        private bool codeFieldSpecified;
        
        private string messageField;
        
        private Msisdn[] msisdnsField;
        
        private bool successfulField;
        
        private bool successfulFieldSpecified;
        
        /// <remarks/>
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codeSpecified {
            get {
                return this.codeFieldSpecified;
            }
            set {
                this.codeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://api.domain.common.alertix.cellvision")]
        public Msisdn[] msisdns {
            get {
                return this.msisdnsField;
            }
            set {
                this.msisdnsField = value;
            }
        }
        
        /// <remarks/>
        public bool successful {
            get {
                return this.successfulField;
            }
            set {
                this.successfulField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool successfulSpecified {
            get {
                return this.successfulFieldSpecified;
            }
            set {
                this.successfulFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void getWhiteListSubscribersCompletedEventHandler(object sender, getWhiteListSubscribersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getWhiteListSubscribersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getWhiteListSubscribersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SubscribersResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SubscribersResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void getWhiteListsCompletedEventHandler(object sender, getWhiteListsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getWhiteListsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getWhiteListsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WhiteListsResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WhiteListsResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void createWhiteListCompletedEventHandler(object sender, createWhiteListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class createWhiteListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal createWhiteListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Response)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void deleteWhiteListCompletedEventHandler(object sender, deleteWhiteListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteWhiteListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteWhiteListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Response)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void deleteWhiteListSubscribersCompletedEventHandler(object sender, deleteWhiteListSubscribersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteWhiteListSubscribersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteWhiteListSubscribersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DeleteResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DeleteResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void addWhiteListSubscribersCompletedEventHandler(object sender, addWhiteListSubscribersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class addWhiteListSubscribersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal addWhiteListSubscribersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AddResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AddResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591