/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LogonDialog.java
 *
 * Created on Jan 20, 2011, 4:02:04 PM
 */

package no.ums.pas.ui;

import no.ums.pas.beans.PropertyUtil;
import no.ums.pas.ums.tools.ImageLoader;
import no.ums.ws.common.ULOGONINFO;
import org.jdesktop.application.Action;
import org.jdesktop.application.Task;
import org.jdesktop.beansbinding.BeanProperty;

import javax.swing.*;
import java.awt.*;
import java.util.Locale;

/**
 * @author staaleu
 */
public class LogonDialog extends javax.swing.JDialog {

    /**
     * Creates new form LogonDialog
     */
    public LogonDialog() {
        initComponents();
        languageInput.setModel(new DefaultComboBoxModel(new Locale[]{Locale.UK, new Locale("no", "NO"), new Locale("nl", "NL")}));

        LogonDialogText.INSTANCE.autoBind("language").to(languageLabel, "text").bind();
        LogonDialogText.INSTANCE.autoBind("username").to(usernameLabel, "text").bind();
        LogonDialogText.INSTANCE.autoBind("customer").to(customerLabel, "text").bind();
        LogonDialogText.INSTANCE.autoBind("password").to(passwordLabel, "text").bind();
        LogonDialogText.INSTANCE.autoBind("login").to(loginButton, "text").bind();

        PropertyUtil.COMBOBOX_SELECTED_ITEM.autobind(languageInput).to(LogonDialogText.INSTANCE, BeanProperty.create("locale")).bind();
        PropertyUtil.JTEXT_TEXT.autobind(customerInput).to(logonBean, BeanProperty.create("customer")).bind();
        PropertyUtil.JTEXT_TEXT.autobind(usernameInput).to(logonBean, BeanProperty.create("username")).bind();
        PropertyUtil.JTEXT_TEXT.autobind(passwordInput).to(logonBean, BeanProperty.create("password")).bind();

        languageInput.setRenderer(new ListCellRenderer() {

            @Override
            public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                final Locale locale = (Locale) value;
                return new JLabel(locale.getDisplayLanguage(LogonDialogText.INSTANCE.getLocale()), ImageLoader.load_icon("nationalities_flags/" + locale + ".gif"), JLabel.LEADING);
            }
        });
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        logonInfo = new ULOGONINFO();
        logonBean = new no.ums.pas.ui.LogonBean();
        languageLabel = new javax.swing.JLabel();
        usernameInput = new javax.swing.JTextField();
        usernameLabel = new javax.swing.JLabel();
        languageInput = new javax.swing.JComboBox();
        customerInput = new javax.swing.JTextField();
        customerLabel = new javax.swing.JLabel();
        passwordInput = new javax.swing.JPasswordField();
        passwordLabel = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        loginErrorLabel = new javax.swing.JLabel();

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, customerInput, PropertyUtil.JTEXT_TEXT, logonBean, org.jdesktop.beansbinding.BeanProperty.create("customer"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, passwordInput, PropertyUtil.JTEXT_TEXT, logonBean, org.jdesktop.beansbinding.BeanProperty.create("password"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, usernameInput, PropertyUtil.JTEXT_TEXT, logonBean, org.jdesktop.beansbinding.BeanProperty.create("username"));
        bindingGroup.addBinding(binding);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        languageLabel.setText("Language");
        languageLabel.setName("languageLabel"); // NOI18N

        usernameInput.setName("usernameInput"); // NOI18N

        usernameLabel.setText("Username:");
        usernameLabel.setName("usernameLabel"); // NOI18N

        languageInput.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"Item 1", "Item 2", "Item 3", "Item 4"}));
        languageInput.setName("languageInput"); // NOI18N
        languageInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                languageInputActionPerformed(evt);
            }
        });

        customerInput.setName("customerInput"); // NOI18N

        customerLabel.setText("Customer: ");
        customerLabel.setName("customerLabel"); // NOI18N

        passwordInput.setName("passwordInput"); // NOI18N

        passwordLabel.setText("Password:");
        passwordLabel.setName("passwordLabel"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance().getContext().getActionMap(LogonDialog.class, this);
        loginButton.setAction(actionMap.get("Login")); // NOI18N
        loginButton.setText("Login");
        loginButton.setName("loginButton"); // NOI18N

        loginErrorLabel.setForeground(new java.awt.Color(205, 50, 50));
        loginErrorLabel.setName("loginErrorLabel"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(129, 129, 129)
                                .addComponent(loginButton, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                                .addGap(145, 145, 145))
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(passwordLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                        .addComponent(customerLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(usernameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(languageLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addComponent(languageInput, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(passwordInput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                                                        .addComponent(customerInput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                                                        .addComponent(usernameInput, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE))))
                                .addContainerGap())
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(loginErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(languageInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(languageLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(usernameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(usernameLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(customerInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(customerLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(passwordInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(passwordLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                                .addComponent(loginErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void languageInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_languageInputActionPerformed
    }//GEN-LAST:event_languageInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LogonDialog dialog = new LogonDialog();
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    @Action(name = "Login")
    public Task login() {
        return new LoginTask(logonBean, new LoginTask.LoginCallback() {
            @Override
            public void success() {
                loginErrorLabel.setText("Success");
            }

            @Override
            public void denied() {
                loginErrorLabel.setText(LogonDialogText.INSTANCE.getLoginFailed());
            }

            @Override
            public void serverError() {
                loginErrorLabel.setText(LogonDialogText.INSTANCE.getLoginServerError());
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField customerInput;
    private javax.swing.JLabel customerLabel;
    private javax.swing.JComboBox languageInput;
    private javax.swing.JLabel languageLabel;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginErrorLabel;
    private no.ums.pas.ui.LogonBean logonBean;
    private ULOGONINFO logonInfo;
    private javax.swing.JPasswordField passwordInput;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField usernameInput;
    private javax.swing.JLabel usernameLabel;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
