
package no.ums.ws.parm;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "parmwsSoap", targetNamespace = "http://ums.no/ws/parm/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ParmwsSoap {


    /**
     * 
     * @return
     *     returns no.ums.ws.parm.ArrayOfPAEVENT
     */
    @WebMethod(operationName = "GetEventListTest", action = "http://ums.no/ws/parm/GetEventListTest")
    @WebResult(name = "GetEventListTestResult", targetNamespace = "http://ums.no/ws/parm/")
    @RequestWrapper(localName = "GetEventListTest", targetNamespace = "http://ums.no/ws/parm/", className = "no.ums.ws.parm.GetEventListTest")
    @ResponseWrapper(localName = "GetEventListTestResponse", targetNamespace = "http://ums.no/ws/parm/", className = "no.ums.ws.parm.GetEventListTestResponse")
    public ArrayOfPAEVENT getEventListTest();

    /**
     * 
     * @param logoninfo
     * @return
     *     returns no.ums.ws.parm.ArrayOfPAEVENT
     */
    @WebMethod(operationName = "GetEventList", action = "http://ums.no/ws/parm/GetEventList")
    @WebResult(name = "GetEventListResult", targetNamespace = "http://ums.no/ws/parm/")
    @RequestWrapper(localName = "GetEventList", targetNamespace = "http://ums.no/ws/parm/", className = "no.ums.ws.parm.GetEventList")
    @ResponseWrapper(localName = "GetEventListResponse", targetNamespace = "http://ums.no/ws/parm/", className = "no.ums.ws.parm.GetEventListResponse")
    public ArrayOfPAEVENT getEventList(
        @WebParam(name = "logoninfo", targetNamespace = "http://ums.no/ws/parm/")
        ULOGONINFO logoninfo);

    /**
     * 
     * @param tas
     * @return
     *     returns no.ums.ws.parm.ExecResponse
     */
    @WebMethod(operationName = "ExecTasSending", action = "http://ums.no/ws/parm/ExecTasSending")
    @WebResult(name = "ExecTasSendingResult", targetNamespace = "http://ums.no/ws/parm/")
    @RequestWrapper(localName = "ExecTasSending", targetNamespace = "http://ums.no/ws/parm/", className = "no.ums.ws.parm.ExecTasSending")
    @ResponseWrapper(localName = "ExecTasSendingResponse", targetNamespace = "http://ums.no/ws/parm/", className = "no.ums.ws.parm.ExecTasSendingResponse")
    public ExecResponse execTasSending(
        @WebParam(name = "tas", targetNamespace = "http://ums.no/ws/parm/")
        UTASSENDING tas);

    /**
     * 
     * @param poly
     * @return
     *     returns no.ums.ws.parm.ExecResponse
     */
    @WebMethod(operationName = "ExecPolygonSending", action = "http://ums.no/ws/parm/ExecPolygonSending")
    @WebResult(name = "ExecPolygonSendingResult", targetNamespace = "http://ums.no/ws/parm/")
    @RequestWrapper(localName = "ExecPolygonSending", targetNamespace = "http://ums.no/ws/parm/", className = "no.ums.ws.parm.ExecPolygonSending")
    @ResponseWrapper(localName = "ExecPolygonSendingResponse", targetNamespace = "http://ums.no/ws/parm/", className = "no.ums.ws.parm.ExecPolygonSendingResponse")
    public ExecResponse execPolygonSending(
        @WebParam(name = "poly", targetNamespace = "http://ums.no/ws/parm/")
        UPOLYGONSENDING poly);

    /**
     * 
     * @param ellipse
     * @return
     *     returns no.ums.ws.parm.ExecResponse
     */
    @WebMethod(operationName = "ExecEllipseSending", action = "http://ums.no/ws/parm/ExecEllipseSending")
    @WebResult(name = "ExecEllipseSendingResult", targetNamespace = "http://ums.no/ws/parm/")
    @RequestWrapper(localName = "ExecEllipseSending", targetNamespace = "http://ums.no/ws/parm/", className = "no.ums.ws.parm.ExecEllipseSending")
    @ResponseWrapper(localName = "ExecEllipseSendingResponse", targetNamespace = "http://ums.no/ws/parm/", className = "no.ums.ws.parm.ExecEllipseSendingResponse")
    public ExecResponse execEllipseSending(
        @WebParam(name = "ellipse", targetNamespace = "http://ums.no/ws/parm/")
        UELLIPSESENDING ellipse);

    /**
     * 
     * @param gis
     * @return
     *     returns no.ums.ws.parm.ExecResponse
     */
    @WebMethod(operationName = "ExecGisSending", action = "http://ums.no/ws/parm/ExecGisSending")
    @WebResult(name = "ExecGisSendingResult", targetNamespace = "http://ums.no/ws/parm/")
    @RequestWrapper(localName = "ExecGisSending", targetNamespace = "http://ums.no/ws/parm/", className = "no.ums.ws.parm.ExecGisSending")
    @ResponseWrapper(localName = "ExecGisSendingResponse", targetNamespace = "http://ums.no/ws/parm/", className = "no.ums.ws.parm.ExecGisSendingResponse")
    public ExecResponse execGisSending(
        @WebParam(name = "gis", targetNamespace = "http://ums.no/ws/parm/")
        UGISSENDING gis);

    /**
     * 
     * @param municipal
     * @return
     *     returns no.ums.ws.parm.ExecResponse
     */
    @WebMethod(operationName = "ExecMunicipalSending", action = "http://ums.no/ws/parm/ExecMunicipalSending")
    @WebResult(name = "ExecMunicipalSendingResult", targetNamespace = "http://ums.no/ws/parm/")
    @RequestWrapper(localName = "ExecMunicipalSending", targetNamespace = "http://ums.no/ws/parm/", className = "no.ums.ws.parm.ExecMunicipalSending")
    @ResponseWrapper(localName = "ExecMunicipalSendingResponse", targetNamespace = "http://ums.no/ws/parm/", className = "no.ums.ws.parm.ExecMunicipalSendingResponse")
    public ExecResponse execMunicipalSending(
        @WebParam(name = "municipal", targetNamespace = "http://ums.no/ws/parm/")
        UMUNICIPALSENDING municipal);

    /**
     * 
     * @param send
     * @return
     *     returns no.ums.ws.parm.ExecResponse
     */
    @WebMethod(operationName = "ExecTestSending", action = "http://ums.no/ws/parm/ExecTestSending")
    @WebResult(name = "ExecTestSendingResult", targetNamespace = "http://ums.no/ws/parm/")
    @RequestWrapper(localName = "ExecTestSending", targetNamespace = "http://ums.no/ws/parm/", className = "no.ums.ws.parm.ExecTestSending")
    @ResponseWrapper(localName = "ExecTestSendingResponse", targetNamespace = "http://ums.no/ws/parm/", className = "no.ums.ws.parm.ExecTestSendingResponse")
    public ExecResponse execTestSending(
        @WebParam(name = "send", targetNamespace = "http://ums.no/ws/parm/")
        UTESTSENDING send);

    /**
     * 
     * @param s
     * @param logon
     * @return
     *     returns no.ums.ws.parm.UMapBounds
     */
    @WebMethod(operationName = "GetMapBoundsFromSending", action = "http://ums.no/ws/parm/GetMapBoundsFromSending")
    @WebResult(name = "GetMapBoundsFromSendingResult", targetNamespace = "http://ums.no/ws/parm/")
    @RequestWrapper(localName = "GetMapBoundsFromSending", targetNamespace = "http://ums.no/ws/parm/", className = "no.ums.ws.parm.GetMapBoundsFromSending")
    @ResponseWrapper(localName = "GetMapBoundsFromSendingResponse", targetNamespace = "http://ums.no/ws/parm/", className = "no.ums.ws.parm.GetMapBoundsFromSendingResponse")
    public UMapBounds getMapBoundsFromSending(
        @WebParam(name = "logon", targetNamespace = "http://ums.no/ws/parm/")
        ULOGONINFO logon,
        @WebParam(name = "s", targetNamespace = "http://ums.no/ws/parm/")
        UMAPSENDING s);

    /**
     * 
     * @param s
     * @param logon
     * @return
     *     returns no.ums.ws.parm.UAdrCount
     */
    @WebMethod(operationName = "GetAdrCountPolygon", action = "http://ums.no/ws/parm/GetAdrCountPolygon")
    @WebResult(name = "GetAdrCountPolygonResult", targetNamespace = "http://ums.no/ws/parm/")
    @RequestWrapper(localName = "GetAdrCountPolygon", targetNamespace = "http://ums.no/ws/parm/", className = "no.ums.ws.parm.GetAdrCountPolygon")
    @ResponseWrapper(localName = "GetAdrCountPolygonResponse", targetNamespace = "http://ums.no/ws/parm/", className = "no.ums.ws.parm.GetAdrCountPolygonResponse")
    public UAdrCount getAdrCountPolygon(
        @WebParam(name = "logon", targetNamespace = "http://ums.no/ws/parm/")
        ULOGONINFO logon,
        @WebParam(name = "s", targetNamespace = "http://ums.no/ws/parm/")
        UPOLYGONSENDING s);

    /**
     * 
     * @param s
     * @param logon
     * @return
     *     returns no.ums.ws.parm.UAdrCount
     */
    @WebMethod(operationName = "GetAdrCountEllipse", action = "http://ums.no/ws/parm/GetAdrCountEllipse")
    @WebResult(name = "GetAdrCountEllipseResult", targetNamespace = "http://ums.no/ws/parm/")
    @RequestWrapper(localName = "GetAdrCountEllipse", targetNamespace = "http://ums.no/ws/parm/", className = "no.ums.ws.parm.GetAdrCountEllipse")
    @ResponseWrapper(localName = "GetAdrCountEllipseResponse", targetNamespace = "http://ums.no/ws/parm/", className = "no.ums.ws.parm.GetAdrCountEllipseResponse")
    public UAdrCount getAdrCountEllipse(
        @WebParam(name = "logon", targetNamespace = "http://ums.no/ws/parm/")
        ULOGONINFO logon,
        @WebParam(name = "s", targetNamespace = "http://ums.no/ws/parm/")
        UELLIPSESENDING s);

    /**
     * 
     * @param s
     * @param logon
     * @return
     *     returns no.ums.ws.parm.UAdrCount
     */
    @WebMethod(operationName = "GetAdrCountGis", action = "http://ums.no/ws/parm/GetAdrCountGis")
    @WebResult(name = "GetAdrCountGisResult", targetNamespace = "http://ums.no/ws/parm/")
    @RequestWrapper(localName = "GetAdrCountGis", targetNamespace = "http://ums.no/ws/parm/", className = "no.ums.ws.parm.GetAdrCountGis")
    @ResponseWrapper(localName = "GetAdrCountGisResponse", targetNamespace = "http://ums.no/ws/parm/", className = "no.ums.ws.parm.GetAdrCountGisResponse")
    public UAdrCount getAdrCountGis(
        @WebParam(name = "logon", targetNamespace = "http://ums.no/ws/parm/")
        ULOGONINFO logon,
        @WebParam(name = "s", targetNamespace = "http://ums.no/ws/parm/")
        UGIS s);

    /**
     * 
     * @param s
     * @param logon
     * @return
     *     returns no.ums.ws.parm.UAdrCount
     */
    @WebMethod(operationName = "GetAdrCountMunicipal", action = "http://ums.no/ws/parm/GetAdrCountMunicipal")
    @WebResult(name = "GetAdrCountMunicipalResult", targetNamespace = "http://ums.no/ws/parm/")
    @RequestWrapper(localName = "GetAdrCountMunicipal", targetNamespace = "http://ums.no/ws/parm/", className = "no.ums.ws.parm.GetAdrCountMunicipal")
    @ResponseWrapper(localName = "GetAdrCountMunicipalResponse", targetNamespace = "http://ums.no/ws/parm/", className = "no.ums.ws.parm.GetAdrCountMunicipalResponse")
    public UAdrCount getAdrCountMunicipal(
        @WebParam(name = "logon", targetNamespace = "http://ums.no/ws/parm/")
        ULOGONINFO logon,
        @WebParam(name = "s", targetNamespace = "http://ums.no/ws/parm/")
        UMUNICIPALSENDING s);

    /**
     * 
     * @param s
     * @param logon
     * @return
     *     returns no.ums.ws.parm.UAdrCount
     */
    @WebMethod(operationName = "GetAdrCountTestsending", action = "http://ums.no/ws/parm/GetAdrCountTestsending")
    @WebResult(name = "GetAdrCountTestsendingResult", targetNamespace = "http://ums.no/ws/parm/")
    @RequestWrapper(localName = "GetAdrCountTestsending", targetNamespace = "http://ums.no/ws/parm/", className = "no.ums.ws.parm.GetAdrCountTestsending")
    @ResponseWrapper(localName = "GetAdrCountTestsendingResponse", targetNamespace = "http://ums.no/ws/parm/", className = "no.ums.ws.parm.GetAdrCountTestsendingResponse")
    public UAdrCount getAdrCountTestsending(
        @WebParam(name = "logon", targetNamespace = "http://ums.no/ws/parm/")
        ULOGONINFO logon,
        @WebParam(name = "s", targetNamespace = "http://ums.no/ws/parm/")
        UTESTSENDING s);

    /**
     * 
     * @param mapsending
     * @param logon
     * @return
     *     returns no.ums.ws.parm.UAdrCount
     */
    @WebMethod(operationName = "GetAdrCount", action = "http://ums.no/ws/parm/GetAdrCount")
    @WebResult(name = "GetAdrCountResult", targetNamespace = "http://ums.no/ws/parm/")
    @RequestWrapper(localName = "GetAdrCount", targetNamespace = "http://ums.no/ws/parm/", className = "no.ums.ws.parm.GetAdrCount")
    @ResponseWrapper(localName = "GetAdrCountResponse", targetNamespace = "http://ums.no/ws/parm/", className = "no.ums.ws.parm.GetAdrCountResponse")
    public UAdrCount getAdrCount(
        @WebParam(name = "logon", targetNamespace = "http://ums.no/ws/parm/")
        ULOGONINFO logon,
        @WebParam(name = "mapsending", targetNamespace = "http://ums.no/ws/parm/")
        UMAPSENDING mapsending);

    /**
     * 
     * @param refno
     * @param logoninfo
     * @param lbaoperator
     * @return
     *     returns no.ums.ws.parm.ExecResponse
     */
    @WebMethod(operationName = "TASResend", action = "http://ums.no/ws/parm/TASResend")
    @WebResult(name = "TASResendResult", targetNamespace = "http://ums.no/ws/parm/")
    @RequestWrapper(localName = "TASResend", targetNamespace = "http://ums.no/ws/parm/", className = "no.ums.ws.parm.TASResend")
    @ResponseWrapper(localName = "TASResendResponse", targetNamespace = "http://ums.no/ws/parm/", className = "no.ums.ws.parm.TASResendResponse")
    public ExecResponse tasResend(
        @WebParam(name = "refno", targetNamespace = "http://ums.no/ws/parm/")
        int refno,
        @WebParam(name = "lbaoperator", targetNamespace = "http://ums.no/ws/parm/")
        int lbaoperator,
        @WebParam(name = "logoninfo", targetNamespace = "http://ums.no/ws/parm/")
        ULOGONINFO logoninfo);

    /**
     * 
     * @param szSchedtime
     * @param szFunction
     * @param szCompid
     * @param szScheddate
     * @param szDeptid
     * @param szPassword
     * @param szUserid
     * @param lDeptpk
     * @param lComppk
     * @param lAlertpk
     * @param lUserpk
     * @return
     *     returns no.ums.ws.parm.ExecResponse
     */
    @WebMethod(operationName = "ExecAlertV2", action = "http://ums.no/ws/parm/ExecAlertV2")
    @WebResult(name = "ExecAlertV2Result", targetNamespace = "http://ums.no/ws/parm/")
    @RequestWrapper(localName = "ExecAlertV2", targetNamespace = "http://ums.no/ws/parm/", className = "no.ums.ws.parm.ExecAlertV2")
    @ResponseWrapper(localName = "ExecAlertV2Response", targetNamespace = "http://ums.no/ws/parm/", className = "no.ums.ws.parm.ExecAlertV2Response")
    public ExecResponse execAlertV2(
        @WebParam(name = "l_alertpk", targetNamespace = "http://ums.no/ws/parm/")
        long lAlertpk,
        @WebParam(name = "l_comppk", targetNamespace = "http://ums.no/ws/parm/")
        int lComppk,
        @WebParam(name = "l_deptpk", targetNamespace = "http://ums.no/ws/parm/")
        int lDeptpk,
        @WebParam(name = "l_userpk", targetNamespace = "http://ums.no/ws/parm/")
        long lUserpk,
        @WebParam(name = "sz_compid", targetNamespace = "http://ums.no/ws/parm/")
        String szCompid,
        @WebParam(name = "sz_userid", targetNamespace = "http://ums.no/ws/parm/")
        String szUserid,
        @WebParam(name = "sz_deptid", targetNamespace = "http://ums.no/ws/parm/")
        String szDeptid,
        @WebParam(name = "sz_password", targetNamespace = "http://ums.no/ws/parm/")
        String szPassword,
        @WebParam(name = "sz_function", targetNamespace = "http://ums.no/ws/parm/")
        String szFunction,
        @WebParam(name = "sz_scheddate", targetNamespace = "http://ums.no/ws/parm/")
        String szScheddate,
        @WebParam(name = "sz_schedtime", targetNamespace = "http://ums.no/ws/parm/")
        String szSchedtime);

    /**
     * 
     * @param szSchedtime
     * @param szFunction
     * @param szScheddate
     * @param logon
     * @param lAlertpk
     * @return
     *     returns no.ums.ws.parm.ExecResponse
     */
    @WebMethod(operationName = "ExecAlertV3", action = "http://ums.no/ws/parm/ExecAlertV3")
    @WebResult(name = "ExecAlertV3Result", targetNamespace = "http://ums.no/ws/parm/")
    @RequestWrapper(localName = "ExecAlertV3", targetNamespace = "http://ums.no/ws/parm/", className = "no.ums.ws.parm.ExecAlertV3")
    @ResponseWrapper(localName = "ExecAlertV3Response", targetNamespace = "http://ums.no/ws/parm/", className = "no.ums.ws.parm.ExecAlertV3Response")
    public ExecResponse execAlertV3(
        @WebParam(name = "l_alertpk", targetNamespace = "http://ums.no/ws/parm/")
        long lAlertpk,
        @WebParam(name = "logon", targetNamespace = "http://ums.no/ws/parm/")
        ULOGONINFO logon,
        @WebParam(name = "sz_function", targetNamespace = "http://ums.no/ws/parm/")
        String szFunction,
        @WebParam(name = "sz_scheddate", targetNamespace = "http://ums.no/ws/parm/")
        String szScheddate,
        @WebParam(name = "sz_schedtime", targetNamespace = "http://ums.no/ws/parm/")
        String szSchedtime);

    /**
     * 
     * @param szSchedtime
     * @param szFunction
     * @param szCompid
     * @param lEventpk
     * @param szScheddate
     * @param szDeptid
     * @param szPassword
     * @param szUserid
     * @return
     *     returns no.ums.ws.parm.ExecResponse
     */
    @WebMethod(operationName = "ExecEventV3", action = "http://ums.no/ws/parm/ExecEventV3")
    @WebResult(name = "ExecEventV3Result", targetNamespace = "http://ums.no/ws/parm/")
    @RequestWrapper(localName = "ExecEventV3", targetNamespace = "http://ums.no/ws/parm/", className = "no.ums.ws.parm.ExecEventV3")
    @ResponseWrapper(localName = "ExecEventV3Response", targetNamespace = "http://ums.no/ws/parm/", className = "no.ums.ws.parm.ExecEventV3Response")
    public ExecResponse execEventV3(
        @WebParam(name = "l_eventpk", targetNamespace = "http://ums.no/ws/parm/")
        long lEventpk,
        @WebParam(name = "sz_compid", targetNamespace = "http://ums.no/ws/parm/")
        String szCompid,
        @WebParam(name = "sz_userid", targetNamespace = "http://ums.no/ws/parm/")
        String szUserid,
        @WebParam(name = "sz_deptid", targetNamespace = "http://ums.no/ws/parm/")
        String szDeptid,
        @WebParam(name = "sz_password", targetNamespace = "http://ums.no/ws/parm/")
        String szPassword,
        @WebParam(name = "sz_function", targetNamespace = "http://ums.no/ws/parm/")
        String szFunction,
        @WebParam(name = "sz_scheddate", targetNamespace = "http://ums.no/ws/parm/")
        String szScheddate,
        @WebParam(name = "sz_schedtime", targetNamespace = "http://ums.no/ws/parm/")
        String szSchedtime);

    /**
     * 
     * @param szSchedtime
     * @param szFunction
     * @param lEventpk
     * @param szScheddate
     * @param logon
     * @return
     *     returns no.ums.ws.parm.ExecResponse
     */
    @WebMethod(operationName = "ExecEventV4", action = "http://ums.no/ws/parm/ExecEventV4")
    @WebResult(name = "ExecEventV4Result", targetNamespace = "http://ums.no/ws/parm/")
    @RequestWrapper(localName = "ExecEventV4", targetNamespace = "http://ums.no/ws/parm/", className = "no.ums.ws.parm.ExecEventV4")
    @ResponseWrapper(localName = "ExecEventV4Response", targetNamespace = "http://ums.no/ws/parm/", className = "no.ums.ws.parm.ExecEventV4Response")
    public ExecResponse execEventV4(
        @WebParam(name = "l_eventpk", targetNamespace = "http://ums.no/ws/parm/")
        long lEventpk,
        @WebParam(name = "logon", targetNamespace = "http://ums.no/ws/parm/")
        ULOGONINFO logon,
        @WebParam(name = "sz_function", targetNamespace = "http://ums.no/ws/parm/")
        String szFunction,
        @WebParam(name = "sz_scheddate", targetNamespace = "http://ums.no/ws/parm/")
        String szScheddate,
        @WebParam(name = "sz_schedtime", targetNamespace = "http://ums.no/ws/parm/")
        String szSchedtime);

    /**
     * 
     * @param szSchedtime
     * @param szFunction
     * @param szCompid
     * @param lEventpk
     * @param szScheddate
     * @param szDeptid
     * @param szPassword
     * @param szUserid
     * @param lDeptpk
     * @param lComppk
     * @param lUserpk
     * @return
     *     returns no.ums.ws.parm.ExecResponse
     */
    @WebMethod(operationName = "ExecEventV2", action = "http://ums.no/ws/parm/ExecEventV2")
    @WebResult(name = "ExecEventV2Result", targetNamespace = "http://ums.no/ws/parm/")
    @RequestWrapper(localName = "ExecEventV2", targetNamespace = "http://ums.no/ws/parm/", className = "no.ums.ws.parm.ExecEventV2")
    @ResponseWrapper(localName = "ExecEventV2Response", targetNamespace = "http://ums.no/ws/parm/", className = "no.ums.ws.parm.ExecEventV2Response")
    public ExecResponse execEventV2(
        @WebParam(name = "l_eventpk", targetNamespace = "http://ums.no/ws/parm/")
        long lEventpk,
        @WebParam(name = "l_comppk", targetNamespace = "http://ums.no/ws/parm/")
        int lComppk,
        @WebParam(name = "l_deptpk", targetNamespace = "http://ums.no/ws/parm/")
        int lDeptpk,
        @WebParam(name = "l_userpk", targetNamespace = "http://ums.no/ws/parm/")
        long lUserpk,
        @WebParam(name = "sz_compid", targetNamespace = "http://ums.no/ws/parm/")
        String szCompid,
        @WebParam(name = "sz_userid", targetNamespace = "http://ums.no/ws/parm/")
        String szUserid,
        @WebParam(name = "sz_deptid", targetNamespace = "http://ums.no/ws/parm/")
        String szDeptid,
        @WebParam(name = "sz_password", targetNamespace = "http://ums.no/ws/parm/")
        String szPassword,
        @WebParam(name = "sz_function", targetNamespace = "http://ums.no/ws/parm/")
        String szFunction,
        @WebParam(name = "sz_scheddate", targetNamespace = "http://ums.no/ws/parm/")
        String szScheddate,
        @WebParam(name = "sz_schedtime", targetNamespace = "http://ums.no/ws/parm/")
        String szSchedtime);

    /**
     * 
     * @param lRefno
     * @param logon
     * @param bConfirm
     * @return
     *     returns no.ums.ws.parm.UConfirmJobResponse
     */
    @WebMethod(operationName = "ConfirmJob_2_0", action = "http://ums.no/ws/parm/ConfirmJob_2_0")
    @WebResult(name = "ConfirmJob_2_0Result", targetNamespace = "http://ums.no/ws/parm/")
    @RequestWrapper(localName = "ConfirmJob_2_0", targetNamespace = "http://ums.no/ws/parm/", className = "no.ums.ws.parm.ConfirmJob20")
    @ResponseWrapper(localName = "ConfirmJob_2_0Response", targetNamespace = "http://ums.no/ws/parm/", className = "no.ums.ws.parm.ConfirmJob20Response")
    public UConfirmJobResponse confirmJob20(
        @WebParam(name = "logon", targetNamespace = "http://ums.no/ws/parm/")
        ULOGONINFO logon,
        @WebParam(name = "l_refno", targetNamespace = "http://ums.no/ws/parm/")
        int lRefno,
        @WebParam(name = "b_confirm", targetNamespace = "http://ums.no/ws/parm/")
        boolean bConfirm);

    /**
     * 
     * @param lRefno
     * @param szJobid
     * @param logon
     * @param bConfirm
     * @return
     *     returns no.ums.ws.parm.UConfirmJobResponse
     */
    @WebMethod(operationName = "ConfirmJob", action = "http://ums.no/ws/parm/ConfirmJob")
    @WebResult(name = "ConfirmJobResult", targetNamespace = "http://ums.no/ws/parm/")
    @RequestWrapper(localName = "ConfirmJob", targetNamespace = "http://ums.no/ws/parm/", className = "no.ums.ws.parm.ConfirmJob")
    @ResponseWrapper(localName = "ConfirmJobResponse", targetNamespace = "http://ums.no/ws/parm/", className = "no.ums.ws.parm.ConfirmJobResponse")
    public UConfirmJobResponse confirmJob(
        @WebParam(name = "logon", targetNamespace = "http://ums.no/ws/parm/")
        ULOGONINFO logon,
        @WebParam(name = "l_refno", targetNamespace = "http://ums.no/ws/parm/")
        int lRefno,
        @WebParam(name = "sz_jobid", targetNamespace = "http://ums.no/ws/parm/")
        String szJobid,
        @WebParam(name = "b_confirm", targetNamespace = "http://ums.no/ws/parm/")
        boolean bConfirm);

}
