
package no.ums.ws.parm;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "parmws", targetNamespace = "http://ums.no/ws/parm/", wsdlLocation = "http://localhost/WS/ExternalExec.asmx?WSDL")
public class Parmws
    extends Service
{

    private final static URL PARMWS_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost/WS/ExternalExec.asmx?WSDL");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        PARMWS_WSDL_LOCATION = url;
    }

    public Parmws(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Parmws() {
        super(PARMWS_WSDL_LOCATION, new QName("http://ums.no/ws/parm/", "parmws"));
    }

    /**
     * 
     * @return
     *     returns ParmwsSoap
     */
    @WebEndpoint(name = "parmwsSoap")
    public ParmwsSoap getParmwsSoap() {
        return (ParmwsSoap)super.getPort(new QName("http://ums.no/ws/parm/", "parmwsSoap"), ParmwsSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ParmwsSoap
     */
    @WebEndpoint(name = "parmwsSoap")
    public ParmwsSoap getParmwsSoap(WebServiceFeature... features) {
        return (ParmwsSoap)super.getPort(new QName("http://ums.no/ws/parm/", "parmwsSoap"), ParmwsSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns ParmwsSoap
     */
    @WebEndpoint(name = "parmwsSoap12")
    public ParmwsSoap getParmwsSoap12() {
        return (ParmwsSoap)super.getPort(new QName("http://ums.no/ws/parm/", "parmwsSoap12"), ParmwsSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ParmwsSoap
     */
    @WebEndpoint(name = "parmwsSoap12")
    public ParmwsSoap getParmwsSoap12(WebServiceFeature... features) {
        return (ParmwsSoap)super.getPort(new QName("http://ums.no/ws/parm/", "parmwsSoap12"), ParmwsSoap.class, features);
    }

}
