
package no.ums.ws.pas.tas;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "TAS", targetNamespace = "http://ums.no/ws/pas/tas", wsdlLocation = "http://localhost/WS/TAS.asmx?WSDL")
public class TAS
    extends Service
{

    private final static URL TAS_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost/WS/TAS.asmx?WSDL");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        TAS_WSDL_LOCATION = url;
    }

    public TAS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TAS() {
        super(TAS_WSDL_LOCATION, new QName("http://ums.no/ws/pas/tas", "TAS"));
    }

    /**
     * 
     * @return
     *     returns TASSoap
     */
    @WebEndpoint(name = "TASSoap")
    public TASSoap getTASSoap() {
        return (TASSoap)super.getPort(new QName("http://ums.no/ws/pas/tas", "TASSoap"), TASSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TASSoap
     */
    @WebEndpoint(name = "TASSoap")
    public TASSoap getTASSoap(WebServiceFeature... features) {
        return (TASSoap)super.getPort(new QName("http://ums.no/ws/pas/tas", "TASSoap"), TASSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns TASSoap
     */
    @WebEndpoint(name = "TASSoap12")
    public TASSoap getTASSoap12() {
        return (TASSoap)super.getPort(new QName("http://ums.no/ws/pas/tas", "TASSoap12"), TASSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TASSoap
     */
    @WebEndpoint(name = "TASSoap12")
    public TASSoap getTASSoap12(WebServiceFeature... features) {
        return (TASSoap)super.getPort(new QName("http://ums.no/ws/pas/tas", "TASSoap12"), TASSoap.class, features);
    }

}
