
package no.ums.ws.pas.tas;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "tasws", targetNamespace = "http://ums.no/ws/pas/tas", wsdlLocation = "http://localhost/WS/Tas.asmx?WSDL")
public class Tasws
    extends Service
{

    private final static URL TASWS_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost/WS/Tas.asmx?WSDL");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        TASWS_WSDL_LOCATION = url;
    }

    public Tasws(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Tasws() {
        super(TASWS_WSDL_LOCATION, new QName("http://ums.no/ws/pas/tas", "tasws"));
    }

    /**
     * 
     * @return
     *     returns TaswsSoap
     */
    @WebEndpoint(name = "taswsSoap")
    public TaswsSoap getTaswsSoap() {
        return (TaswsSoap)super.getPort(new QName("http://ums.no/ws/pas/tas", "taswsSoap"), TaswsSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TaswsSoap
     */
    @WebEndpoint(name = "taswsSoap")
    public TaswsSoap getTaswsSoap(WebServiceFeature... features) {
        return (TaswsSoap)super.getPort(new QName("http://ums.no/ws/pas/tas", "taswsSoap"), TaswsSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns TaswsSoap
     */
    @WebEndpoint(name = "taswsSoap12")
    public TaswsSoap getTaswsSoap12() {
        return (TaswsSoap)super.getPort(new QName("http://ums.no/ws/pas/tas", "taswsSoap12"), TaswsSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TaswsSoap
     */
    @WebEndpoint(name = "taswsSoap12")
    public TaswsSoap getTaswsSoap12(WebServiceFeature... features) {
        return (TaswsSoap)super.getPort(new QName("http://ums.no/ws/pas/tas", "taswsSoap12"), TaswsSoap.class, features);
    }

}
