//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ibag:1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="ibag:1.0", IsNullable=false)]
public partial class IBAG_Alert_Attributes {
    
    private string iBAG_protocol_versionField;
    
    private string iBAG_sending_gateway_idField;
    
    private byte[] iBAG_message_numberField;
    
    private byte[] iBAG_referenced_message_numberField;
    
    private string iBAG_referenced_message_cap_identifierField;
    
    private string iBAG_senderField;
    
    private System.DateTime iBAG_sent_date_timeField;
    
    private IBAG_Alert_AttributesIBAG_status iBAG_statusField;
    
    private IBAG_Alert_AttributesIBAG_message_type iBAG_message_typeField;
    
    private IBAG_Alert_AttributesIBAG_status_report[] iBAG_status_reportField;
    
    private string[] iBAG_response_codeField;
    
    private string[] iBAG_noteField;
    
    private string iBAG_cap_alert_uriField;
    
    private string iBAG_cap_identifierField;
    
    private System.DateTime iBAG_cap_sent_date_timeField;
    
    private bool iBAG_cap_sent_date_timeFieldSpecified;
    
    private IBAG_Alert_AttributesIBAG_alert_info iBAG_alert_infoField;
    
    private IBAG_Alert_AttributesIBAG_Digital_Signature iBAG_Digital_SignatureField;
    
    /// <remarks/>
    public string IBAG_protocol_version {
        get {
            return this.iBAG_protocol_versionField;
        }
        set {
            this.iBAG_protocol_versionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
    public string IBAG_sending_gateway_id {
        get {
            return this.iBAG_sending_gateway_idField;
        }
        set {
            this.iBAG_sending_gateway_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="hexBinary")]
    public byte[] IBAG_message_number {
        get {
            return this.iBAG_message_numberField;
        }
        set {
            this.iBAG_message_numberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="hexBinary")]
    public byte[] IBAG_referenced_message_number {
        get {
            return this.iBAG_referenced_message_numberField;
        }
        set {
            this.iBAG_referenced_message_numberField = value;
        }
    }
    
    /// <remarks/>
    public string IBAG_referenced_message_cap_identifier {
        get {
            return this.iBAG_referenced_message_cap_identifierField;
        }
        set {
            this.iBAG_referenced_message_cap_identifierField = value;
        }
    }
    
    /// <remarks/>
    public string IBAG_sender {
        get {
            return this.iBAG_senderField;
        }
        set {
            this.iBAG_senderField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime IBAG_sent_date_time {
        get {
            return this.iBAG_sent_date_timeField;
        }
        set {
            this.iBAG_sent_date_timeField = value;
        }
    }
    
    /// <remarks/>
    public IBAG_Alert_AttributesIBAG_status IBAG_status {
        get {
            return this.iBAG_statusField;
        }
        set {
            this.iBAG_statusField = value;
        }
    }
    
    /// <remarks/>
    public IBAG_Alert_AttributesIBAG_message_type IBAG_message_type {
        get {
            return this.iBAG_message_typeField;
        }
        set {
            this.iBAG_message_typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("IBAG_status_report")]
    public IBAG_Alert_AttributesIBAG_status_report[] IBAG_status_report {
        get {
            return this.iBAG_status_reportField;
        }
        set {
            this.iBAG_status_reportField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("IBAG_response_code")]
    public string[] IBAG_response_code {
        get {
            return this.iBAG_response_codeField;
        }
        set {
            this.iBAG_response_codeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("IBAG_note")]
    public string[] IBAG_note {
        get {
            return this.iBAG_noteField;
        }
        set {
            this.iBAG_noteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
    public string IBAG_cap_alert_uri {
        get {
            return this.iBAG_cap_alert_uriField;
        }
        set {
            this.iBAG_cap_alert_uriField = value;
        }
    }
    
    /// <remarks/>
    public string IBAG_cap_identifier {
        get {
            return this.iBAG_cap_identifierField;
        }
        set {
            this.iBAG_cap_identifierField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime IBAG_cap_sent_date_time {
        get {
            return this.iBAG_cap_sent_date_timeField;
        }
        set {
            this.iBAG_cap_sent_date_timeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IBAG_cap_sent_date_timeSpecified {
        get {
            return this.iBAG_cap_sent_date_timeFieldSpecified;
        }
        set {
            this.iBAG_cap_sent_date_timeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public IBAG_Alert_AttributesIBAG_alert_info IBAG_alert_info {
        get {
            return this.iBAG_alert_infoField;
        }
        set {
            this.iBAG_alert_infoField = value;
        }
    }
    
    /// <remarks/>
    public IBAG_Alert_AttributesIBAG_Digital_Signature IBAG_Digital_Signature {
        get {
            return this.iBAG_Digital_SignatureField;
        }
        set {
            this.iBAG_Digital_SignatureField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ibag:1.0")]
public enum IBAG_Alert_AttributesIBAG_status {
    
    /// <remarks/>
    Actual,
    
    /// <remarks/>
    System,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Network Test")]
    NetworkTest,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ibag:1.0")]
public enum IBAG_Alert_AttributesIBAG_message_type {
    
    /// <remarks/>
    Alert,
    
    /// <remarks/>
    Update,
    
    /// <remarks/>
    Cancel,
    
    /// <remarks/>
    Ack,
    
    /// <remarks/>
    Error,
    
    /// <remarks/>
    RMT,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Link Test")]
    LinkTest,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Transmission Control - Cease")]
    TransmissionControlCease,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Transmission Control - Resume")]
    TransmissionControlResume,
    
    /// <remarks/>
    Report,
    
    /// <remarks/>
    EMS,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ibag:1.0")]
public partial class IBAG_Alert_AttributesIBAG_status_report {
    
    private IBAG_Alert_AttributesIBAG_status_reportIBAG_network_type iBAG_network_typeField;
    
    private int iBAG_cell_countField;
    
    private int iBAG_cell_broadcast_info_countField;
    
    private int iBAG_cell_broadcast_percentageField;
    
    private int iBAG_cell_nobroadcast_percentageField;
    
    private int iBAG_cell_broadcast_info_unknown_percentageField;
    
    private int iBAG_cell_broadcast_info_unavailable_percentageField;
    
    private int iBAG_broadcast_countField;
    
    /// <remarks/>
    public IBAG_Alert_AttributesIBAG_status_reportIBAG_network_type IBAG_network_type {
        get {
            return this.iBAG_network_typeField;
        }
        set {
            this.iBAG_network_typeField = value;
        }
    }
    
    /// <remarks/>
    public int IBAG_cell_count {
        get {
            return this.iBAG_cell_countField;
        }
        set {
            this.iBAG_cell_countField = value;
        }
    }
    
    /// <remarks/>
    public int IBAG_cell_broadcast_info_count {
        get {
            return this.iBAG_cell_broadcast_info_countField;
        }
        set {
            this.iBAG_cell_broadcast_info_countField = value;
        }
    }
    
    /// <remarks/>
    public int IBAG_cell_broadcast_percentage {
        get {
            return this.iBAG_cell_broadcast_percentageField;
        }
        set {
            this.iBAG_cell_broadcast_percentageField = value;
        }
    }
    
    /// <remarks/>
    public int IBAG_cell_nobroadcast_percentage {
        get {
            return this.iBAG_cell_nobroadcast_percentageField;
        }
        set {
            this.iBAG_cell_nobroadcast_percentageField = value;
        }
    }
    
    /// <remarks/>
    public int IBAG_cell_broadcast_info_unknown_percentage {
        get {
            return this.iBAG_cell_broadcast_info_unknown_percentageField;
        }
        set {
            this.iBAG_cell_broadcast_info_unknown_percentageField = value;
        }
    }
    
    /// <remarks/>
    public int IBAG_cell_broadcast_info_unavailable_percentage {
        get {
            return this.iBAG_cell_broadcast_info_unavailable_percentageField;
        }
        set {
            this.iBAG_cell_broadcast_info_unavailable_percentageField = value;
        }
    }
    
    /// <remarks/>
    public int IBAG_broadcast_count {
        get {
            return this.iBAG_broadcast_countField;
        }
        set {
            this.iBAG_broadcast_countField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ibag:1.0")]
public enum IBAG_Alert_AttributesIBAG_status_reportIBAG_network_type {
    
    /// <remarks/>
    GSM,
    
    /// <remarks/>
    UMTS,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ibag:1.0")]
public partial class IBAG_Alert_AttributesIBAG_alert_info {
    
    private IBAG_Alert_AttributesIBAG_alert_infoIBAG_priority iBAG_priorityField;
    
    private bool iBAG_priorityFieldSpecified;
    
    private IBAG_Alert_AttributesIBAG_alert_infoIBAG_category iBAG_categoryField;
    
    private IBAG_Alert_AttributesIBAG_alert_infoIBAG_event_code iBAG_event_codeField;
    
    private IBAG_Alert_AttributesIBAG_alert_infoIBAG_response_type iBAG_response_typeField;
    
    private bool iBAG_response_typeFieldSpecified;
    
    private IBAG_Alert_AttributesIBAG_alert_infoIBAG_severity iBAG_severityField;
    
    private IBAG_Alert_AttributesIBAG_alert_infoIBAG_urgency iBAG_urgencyField;
    
    private IBAG_Alert_AttributesIBAG_alert_infoIBAG_certainty iBAG_certaintyField;
    
    private System.DateTime iBAG_expires_date_timeField;
    
    private string iBAG_sender_nameField;
    
    private IBAG_Alert_AttributesIBAG_alert_infoIBAG_text_language iBAG_text_languageField;
    
    private string iBAG_text_alert_message_lengthField;
    
    private string iBAG_text_alert_messageField;
    
    private string iBAG_channel_categoryField;
    
    private int iBAG_gsm_repetition_periodField;
    
    private bool iBAG_gsm_repetition_periodFieldSpecified;
    
    private int iBAG_umts_repetition_periodField;
    
    private bool iBAG_umts_repetition_periodFieldSpecified;
    
    private int iBAG_broadcast_countField;
    
    private bool iBAG_broadcast_countFieldSpecified;
    
    private IBAG_Alert_AttributesIBAG_alert_infoIBAG_coordinate_system iBAG_coordinate_systemField;
    
    private bool iBAG_coordinate_systemFieldSpecified;
    
    private IBAG_Alert_AttributesIBAG_alert_infoIBAG_Alert_Area[] iBAG_Alert_AreaField;
    
    /// <remarks/>
    public IBAG_Alert_AttributesIBAG_alert_infoIBAG_priority IBAG_priority {
        get {
            return this.iBAG_priorityField;
        }
        set {
            this.iBAG_priorityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IBAG_prioritySpecified {
        get {
            return this.iBAG_priorityFieldSpecified;
        }
        set {
            this.iBAG_priorityFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public IBAG_Alert_AttributesIBAG_alert_infoIBAG_category IBAG_category {
        get {
            return this.iBAG_categoryField;
        }
        set {
            this.iBAG_categoryField = value;
        }
    }
    
    /// <remarks/>
    public IBAG_Alert_AttributesIBAG_alert_infoIBAG_event_code IBAG_event_code {
        get {
            return this.iBAG_event_codeField;
        }
        set {
            this.iBAG_event_codeField = value;
        }
    }
    
    /// <remarks/>
    public IBAG_Alert_AttributesIBAG_alert_infoIBAG_response_type IBAG_response_type {
        get {
            return this.iBAG_response_typeField;
        }
        set {
            this.iBAG_response_typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IBAG_response_typeSpecified {
        get {
            return this.iBAG_response_typeFieldSpecified;
        }
        set {
            this.iBAG_response_typeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public IBAG_Alert_AttributesIBAG_alert_infoIBAG_severity IBAG_severity {
        get {
            return this.iBAG_severityField;
        }
        set {
            this.iBAG_severityField = value;
        }
    }
    
    /// <remarks/>
    public IBAG_Alert_AttributesIBAG_alert_infoIBAG_urgency IBAG_urgency {
        get {
            return this.iBAG_urgencyField;
        }
        set {
            this.iBAG_urgencyField = value;
        }
    }
    
    /// <remarks/>
    public IBAG_Alert_AttributesIBAG_alert_infoIBAG_certainty IBAG_certainty {
        get {
            return this.iBAG_certaintyField;
        }
        set {
            this.iBAG_certaintyField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime IBAG_expires_date_time {
        get {
            return this.iBAG_expires_date_timeField;
        }
        set {
            this.iBAG_expires_date_timeField = value;
        }
    }
    
    /// <remarks/>
    public string IBAG_sender_name {
        get {
            return this.iBAG_sender_nameField;
        }
        set {
            this.iBAG_sender_nameField = value;
        }
    }
    
    /// <remarks/>
    public IBAG_Alert_AttributesIBAG_alert_infoIBAG_text_language IBAG_text_language {
        get {
            return this.iBAG_text_languageField;
        }
        set {
            this.iBAG_text_languageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string IBAG_text_alert_message_length {
        get {
            return this.iBAG_text_alert_message_lengthField;
        }
        set {
            this.iBAG_text_alert_message_lengthField = value;
        }
    }
    
    /// <remarks/>
    public string IBAG_text_alert_message {
        get {
            return this.iBAG_text_alert_messageField;
        }
        set {
            this.iBAG_text_alert_messageField = value;
        }
    }
    
    /// <remarks/>
    public string IBAG_channel_category {
        get {
            return this.iBAG_channel_categoryField;
        }
        set {
            this.iBAG_channel_categoryField = value;
        }
    }
    
    /// <remarks/>
    public int IBAG_gsm_repetition_period {
        get {
            return this.iBAG_gsm_repetition_periodField;
        }
        set {
            this.iBAG_gsm_repetition_periodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IBAG_gsm_repetition_periodSpecified {
        get {
            return this.iBAG_gsm_repetition_periodFieldSpecified;
        }
        set {
            this.iBAG_gsm_repetition_periodFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int IBAG_umts_repetition_period {
        get {
            return this.iBAG_umts_repetition_periodField;
        }
        set {
            this.iBAG_umts_repetition_periodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IBAG_umts_repetition_periodSpecified {
        get {
            return this.iBAG_umts_repetition_periodFieldSpecified;
        }
        set {
            this.iBAG_umts_repetition_periodFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int IBAG_broadcast_count {
        get {
            return this.iBAG_broadcast_countField;
        }
        set {
            this.iBAG_broadcast_countField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IBAG_broadcast_countSpecified {
        get {
            return this.iBAG_broadcast_countFieldSpecified;
        }
        set {
            this.iBAG_broadcast_countFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public IBAG_Alert_AttributesIBAG_alert_infoIBAG_coordinate_system IBAG_coordinate_system {
        get {
            return this.iBAG_coordinate_systemField;
        }
        set {
            this.iBAG_coordinate_systemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IBAG_coordinate_systemSpecified {
        get {
            return this.iBAG_coordinate_systemFieldSpecified;
        }
        set {
            this.iBAG_coordinate_systemFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("IBAG_Alert_Area")]
    public IBAG_Alert_AttributesIBAG_alert_infoIBAG_Alert_Area[] IBAG_Alert_Area {
        get {
            return this.iBAG_Alert_AreaField;
        }
        set {
            this.iBAG_Alert_AreaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ibag:1.0")]
public enum IBAG_Alert_AttributesIBAG_alert_infoIBAG_priority {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("High Priority")]
    HighPriority,
    
    /// <remarks/>
    Normal,
    
    /// <remarks/>
    Background,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ibag:1.0")]
public enum IBAG_Alert_AttributesIBAG_alert_infoIBAG_category {
    
    /// <remarks/>
    Geo,
    
    /// <remarks/>
    Met,
    
    /// <remarks/>
    Safety,
    
    /// <remarks/>
    Security,
    
    /// <remarks/>
    Rescue,
    
    /// <remarks/>
    Fire,
    
    /// <remarks/>
    Health,
    
    /// <remarks/>
    Env,
    
    /// <remarks/>
    Transport,
    
    /// <remarks/>
    Infra,
    
    /// <remarks/>
    CBRNE,
    
    /// <remarks/>
    Other,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ibag:1.0")]
public enum IBAG_Alert_AttributesIBAG_alert_infoIBAG_event_code {
    
    /// <remarks/>
    CDW,
    
    /// <remarks/>
    CEM,
    
    /// <remarks/>
    EVI,
    
    /// <remarks/>
    HMW,
    
    /// <remarks/>
    LEW,
    
    /// <remarks/>
    LAE,
    
    /// <remarks/>
    NUW,
    
    /// <remarks/>
    RHW,
    
    /// <remarks/>
    SPW,
    
    /// <remarks/>
    AVW,
    
    /// <remarks/>
    BZW,
    
    /// <remarks/>
    CAE,
    
    /// <remarks/>
    CFW,
    
    /// <remarks/>
    DSW,
    
    /// <remarks/>
    EQW,
    
    /// <remarks/>
    FRW,
    
    /// <remarks/>
    FFW,
    
    /// <remarks/>
    FLW,
    
    /// <remarks/>
    HWW,
    
    /// <remarks/>
    HUW,
    
    /// <remarks/>
    SVR,
    
    /// <remarks/>
    SMW,
    
    /// <remarks/>
    TOR,
    
    /// <remarks/>
    TRW,
    
    /// <remarks/>
    TSW,
    
    /// <remarks/>
    VOW,
    
    /// <remarks/>
    WSW,
    
    /// <remarks/>
    EAN,
    
    /// <remarks/>
    RMT,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ibag:1.0")]
public enum IBAG_Alert_AttributesIBAG_alert_infoIBAG_response_type {
    
    /// <remarks/>
    Shelter,
    
    /// <remarks/>
    Evacuate,
    
    /// <remarks/>
    Prepare,
    
    /// <remarks/>
    Execute,
    
    /// <remarks/>
    Monitor,
    
    /// <remarks/>
    Avoid,
    
    /// <remarks/>
    Assess,
    
    /// <remarks/>
    None,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ibag:1.0")]
public enum IBAG_Alert_AttributesIBAG_alert_infoIBAG_severity {
    
    /// <remarks/>
    Extreme,
    
    /// <remarks/>
    Severe,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ibag:1.0")]
public enum IBAG_Alert_AttributesIBAG_alert_infoIBAG_urgency {
    
    /// <remarks/>
    Immediate,
    
    /// <remarks/>
    Expected,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ibag:1.0")]
public enum IBAG_Alert_AttributesIBAG_alert_infoIBAG_certainty {
    
    /// <remarks/>
    Observed,
    
    /// <remarks/>
    Likely,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ibag:1.0")]
public enum IBAG_Alert_AttributesIBAG_alert_infoIBAG_text_language {
    
    /// <remarks/>
    English,
    
    /// <remarks/>
    Spanish,
    
    /// <remarks/>
    French,
    
    /// <remarks/>
    Dutch,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ibag:1.0")]
public enum IBAG_Alert_AttributesIBAG_alert_infoIBAG_coordinate_system {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("WGS-84")]
    WGS84,
    
    /// <remarks/>
    UTM,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("NAD-27")]
    NAD27,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("NAD-83")]
    NAD83,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ibag:1.0")]
public partial class IBAG_Alert_AttributesIBAG_alert_infoIBAG_Alert_Area {
    
    private string iBAG_area_descriptionField;
    
    private string iBAG_utm_zoneField;
    
    private string[] iBAG_polygonField;
    
    private string[] iBAG_circleField;
    
    private string[] iBAG_geocodeField;
    
    private IBAG_Alert_AttributesIBAG_alert_infoIBAG_Alert_AreaIBAG_cell_list[] iBAG_cell_listField;
    
    /// <remarks/>
    public string IBAG_area_description {
        get {
            return this.iBAG_area_descriptionField;
        }
        set {
            this.iBAG_area_descriptionField = value;
        }
    }
    
    /// <remarks/>
    public string IBAG_utm_zone {
        get {
            return this.iBAG_utm_zoneField;
        }
        set {
            this.iBAG_utm_zoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("IBAG_polygon")]
    public string[] IBAG_polygon {
        get {
            return this.iBAG_polygonField;
        }
        set {
            this.iBAG_polygonField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("IBAG_circle")]
    public string[] IBAG_circle {
        get {
            return this.iBAG_circleField;
        }
        set {
            this.iBAG_circleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("IBAG_geocode")]
    public string[] IBAG_geocode {
        get {
            return this.iBAG_geocodeField;
        }
        set {
            this.iBAG_geocodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("IBAG_cell_list")]
    public IBAG_Alert_AttributesIBAG_alert_infoIBAG_Alert_AreaIBAG_cell_list[] IBAG_cell_list {
        get {
            return this.iBAG_cell_listField;
        }
        set {
            this.iBAG_cell_listField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ibag:1.0")]
public partial class IBAG_Alert_AttributesIBAG_alert_infoIBAG_Alert_AreaIBAG_cell_list {
    
    private IBAG_Alert_AttributesIBAG_alert_infoIBAG_Alert_AreaIBAG_cell_listIBAG_network_type iBAG_network_typeField;
    
    private string iBAG_network_element_identifierField;
    
    private string iBAG_region_identifierField;
    
    private string[] iBAG_cell_identifierField;
    
    /// <remarks/>
    public IBAG_Alert_AttributesIBAG_alert_infoIBAG_Alert_AreaIBAG_cell_listIBAG_network_type IBAG_network_type {
        get {
            return this.iBAG_network_typeField;
        }
        set {
            this.iBAG_network_typeField = value;
        }
    }
    
    /// <remarks/>
    public string IBAG_network_element_identifier {
        get {
            return this.iBAG_network_element_identifierField;
        }
        set {
            this.iBAG_network_element_identifierField = value;
        }
    }
    
    /// <remarks/>
    public string IBAG_region_identifier {
        get {
            return this.iBAG_region_identifierField;
        }
        set {
            this.iBAG_region_identifierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("IBAG_cell_identifier")]
    public string[] IBAG_cell_identifier {
        get {
            return this.iBAG_cell_identifierField;
        }
        set {
            this.iBAG_cell_identifierField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ibag:1.0")]
public enum IBAG_Alert_AttributesIBAG_alert_infoIBAG_Alert_AreaIBAG_cell_listIBAG_network_type {
    
    /// <remarks/>
    GSM,
    
    /// <remarks/>
    UMTS,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ibag:1.0")]
public partial class IBAG_Alert_AttributesIBAG_Digital_Signature {
    
    private System.Xml.XmlElement[] anyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
}
