//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.237.
// 
#pragma warning disable 1591

namespace UMSAlertiX.AlertiXAlertApi {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AlertApiHttpBinding", Namespace="http://api.alertix.cellvision")]
    public partial class AlertApi : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback prepareAreaAlertOperationCompleted;
        
        private System.Threading.SendOrPostCallback executeAdditionalAlertOperationCompleted;
        
        private System.Threading.SendOrPostCallback prepareCustomAlertOperationCompleted;
        
        private System.Threading.SendOrPostCallback executeCustomAlertOperationCompleted;
        
        private System.Threading.SendOrPostCallback cancelPreparedAlertOperationCompleted;
        
        private System.Threading.SendOrPostCallback executePreparedAlertOperationCompleted;
        
        private System.Threading.SendOrPostCallback executeAreaAlertOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AlertApi() {
            this.Url = global::UMSAlertiX.Properties.Settings.Default.UMSAlertiX_AlertiXAlertApi_AlertApi;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event prepareAreaAlertCompletedEventHandler prepareAreaAlertCompleted;
        
        /// <remarks/>
        public event executeAdditionalAlertCompletedEventHandler executeAdditionalAlertCompleted;
        
        /// <remarks/>
        public event prepareCustomAlertCompletedEventHandler prepareCustomAlertCompleted;
        
        /// <remarks/>
        public event executeCustomAlertCompletedEventHandler executeCustomAlertCompleted;
        
        /// <remarks/>
        public event cancelPreparedAlertCompletedEventHandler cancelPreparedAlertCompleted;
        
        /// <remarks/>
        public event executePreparedAlertCompletedEventHandler executePreparedAlertCompleted;
        
        /// <remarks/>
        public event executeAreaAlertCompletedEventHandler executeAreaAlertCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://api.alertix.cellvision", ResponseNamespace="http://api.alertix.cellvision", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public AlertResponse prepareAreaAlert([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] AreaName in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] AlertMsg in1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] WhiteLists in2, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] AdditionalSubscribers in3) {
            object[] results = this.Invoke("prepareAreaAlert", new object[] {
                        in0,
                        in1,
                        in2,
                        in3});
            return ((AlertResponse)(results[0]));
        }
        
        /// <remarks/>
        public void prepareAreaAlertAsync(AreaName in0, AlertMsg in1, WhiteLists in2, AdditionalSubscribers in3) {
            this.prepareAreaAlertAsync(in0, in1, in2, in3, null);
        }
        
        /// <remarks/>
        public void prepareAreaAlertAsync(AreaName in0, AlertMsg in1, WhiteLists in2, AdditionalSubscribers in3, object userState) {
            if ((this.prepareAreaAlertOperationCompleted == null)) {
                this.prepareAreaAlertOperationCompleted = new System.Threading.SendOrPostCallback(this.OnprepareAreaAlertOperationCompleted);
            }
            this.InvokeAsync("prepareAreaAlert", new object[] {
                        in0,
                        in1,
                        in2,
                        in3}, this.prepareAreaAlertOperationCompleted, userState);
        }
        
        private void OnprepareAreaAlertOperationCompleted(object arg) {
            if ((this.prepareAreaAlertCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.prepareAreaAlertCompleted(this, new prepareAreaAlertCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://api.alertix.cellvision", ResponseNamespace="http://api.alertix.cellvision", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public AlertResponse executeAdditionalAlert([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] JobId in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] AlertMsg in1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] WhiteLists in2, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<ExecuteMode> in3) {
            object[] results = this.Invoke("executeAdditionalAlert", new object[] {
                        in0,
                        in1,
                        in2,
                        in3});
            return ((AlertResponse)(results[0]));
        }
        
        /// <remarks/>
        public void executeAdditionalAlertAsync(JobId in0, AlertMsg in1, WhiteLists in2, System.Nullable<ExecuteMode> in3) {
            this.executeAdditionalAlertAsync(in0, in1, in2, in3, null);
        }
        
        /// <remarks/>
        public void executeAdditionalAlertAsync(JobId in0, AlertMsg in1, WhiteLists in2, System.Nullable<ExecuteMode> in3, object userState) {
            if ((this.executeAdditionalAlertOperationCompleted == null)) {
                this.executeAdditionalAlertOperationCompleted = new System.Threading.SendOrPostCallback(this.OnexecuteAdditionalAlertOperationCompleted);
            }
            this.InvokeAsync("executeAdditionalAlert", new object[] {
                        in0,
                        in1,
                        in2,
                        in3}, this.executeAdditionalAlertOperationCompleted, userState);
        }
        
        private void OnexecuteAdditionalAlertOperationCompleted(object arg) {
            if ((this.executeAdditionalAlertCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.executeAdditionalAlertCompleted(this, new executeAdditionalAlertCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://api.alertix.cellvision", ResponseNamespace="http://api.alertix.cellvision", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public AlertResponse prepareCustomAlert([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] AreaName in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] AlertMsg in1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] WhiteLists in2, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Polygon in3, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] AdditionalSubscribers in4) {
            object[] results = this.Invoke("prepareCustomAlert", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4});
            return ((AlertResponse)(results[0]));
        }
        
        /// <remarks/>
        public void prepareCustomAlertAsync(AreaName in0, AlertMsg in1, WhiteLists in2, Polygon in3, AdditionalSubscribers in4) {
            this.prepareCustomAlertAsync(in0, in1, in2, in3, in4, null);
        }
        
        /// <remarks/>
        public void prepareCustomAlertAsync(AreaName in0, AlertMsg in1, WhiteLists in2, Polygon in3, AdditionalSubscribers in4, object userState) {
            if ((this.prepareCustomAlertOperationCompleted == null)) {
                this.prepareCustomAlertOperationCompleted = new System.Threading.SendOrPostCallback(this.OnprepareCustomAlertOperationCompleted);
            }
            this.InvokeAsync("prepareCustomAlert", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4}, this.prepareCustomAlertOperationCompleted, userState);
        }
        
        private void OnprepareCustomAlertOperationCompleted(object arg) {
            if ((this.prepareCustomAlertCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.prepareCustomAlertCompleted(this, new prepareCustomAlertCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://api.alertix.cellvision", ResponseNamespace="http://api.alertix.cellvision", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public AlertResponse executeCustomAlert([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] AreaName in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] AlertMsg in1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] WhiteLists in2, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Polygon in3, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] AdditionalSubscribers in4, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<ExecuteMode> in5) {
            object[] results = this.Invoke("executeCustomAlert", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4,
                        in5});
            return ((AlertResponse)(results[0]));
        }
        
        /// <remarks/>
        public void executeCustomAlertAsync(AreaName in0, AlertMsg in1, WhiteLists in2, Polygon in3, AdditionalSubscribers in4, System.Nullable<ExecuteMode> in5) {
            this.executeCustomAlertAsync(in0, in1, in2, in3, in4, in5, null);
        }
        
        /// <remarks/>
        public void executeCustomAlertAsync(AreaName in0, AlertMsg in1, WhiteLists in2, Polygon in3, AdditionalSubscribers in4, System.Nullable<ExecuteMode> in5, object userState) {
            if ((this.executeCustomAlertOperationCompleted == null)) {
                this.executeCustomAlertOperationCompleted = new System.Threading.SendOrPostCallback(this.OnexecuteCustomAlertOperationCompleted);
            }
            this.InvokeAsync("executeCustomAlert", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4,
                        in5}, this.executeCustomAlertOperationCompleted, userState);
        }
        
        private void OnexecuteCustomAlertOperationCompleted(object arg) {
            if ((this.executeCustomAlertCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.executeCustomAlertCompleted(this, new executeCustomAlertCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://api.alertix.cellvision", ResponseNamespace="http://api.alertix.cellvision", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public Response cancelPreparedAlert([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] JobId in0) {
            object[] results = this.Invoke("cancelPreparedAlert", new object[] {
                        in0});
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public void cancelPreparedAlertAsync(JobId in0) {
            this.cancelPreparedAlertAsync(in0, null);
        }
        
        /// <remarks/>
        public void cancelPreparedAlertAsync(JobId in0, object userState) {
            if ((this.cancelPreparedAlertOperationCompleted == null)) {
                this.cancelPreparedAlertOperationCompleted = new System.Threading.SendOrPostCallback(this.OncancelPreparedAlertOperationCompleted);
            }
            this.InvokeAsync("cancelPreparedAlert", new object[] {
                        in0}, this.cancelPreparedAlertOperationCompleted, userState);
        }
        
        private void OncancelPreparedAlertOperationCompleted(object arg) {
            if ((this.cancelPreparedAlertCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cancelPreparedAlertCompleted(this, new cancelPreparedAlertCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://api.alertix.cellvision", ResponseNamespace="http://api.alertix.cellvision", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public Response executePreparedAlert([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] JobId in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<ExecuteMode> in1) {
            object[] results = this.Invoke("executePreparedAlert", new object[] {
                        in0,
                        in1});
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public void executePreparedAlertAsync(JobId in0, System.Nullable<ExecuteMode> in1) {
            this.executePreparedAlertAsync(in0, in1, null);
        }
        
        /// <remarks/>
        public void executePreparedAlertAsync(JobId in0, System.Nullable<ExecuteMode> in1, object userState) {
            if ((this.executePreparedAlertOperationCompleted == null)) {
                this.executePreparedAlertOperationCompleted = new System.Threading.SendOrPostCallback(this.OnexecutePreparedAlertOperationCompleted);
            }
            this.InvokeAsync("executePreparedAlert", new object[] {
                        in0,
                        in1}, this.executePreparedAlertOperationCompleted, userState);
        }
        
        private void OnexecutePreparedAlertOperationCompleted(object arg) {
            if ((this.executePreparedAlertCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.executePreparedAlertCompleted(this, new executePreparedAlertCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://api.alertix.cellvision", ResponseNamespace="http://api.alertix.cellvision", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public AlertResponse executeAreaAlert([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] AreaName in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] AlertMsg in1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] WhiteLists in2, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] AdditionalSubscribers in3, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<ExecuteMode> in4) {
            object[] results = this.Invoke("executeAreaAlert", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4});
            return ((AlertResponse)(results[0]));
        }
        
        /// <remarks/>
        public void executeAreaAlertAsync(AreaName in0, AlertMsg in1, WhiteLists in2, AdditionalSubscribers in3, System.Nullable<ExecuteMode> in4) {
            this.executeAreaAlertAsync(in0, in1, in2, in3, in4, null);
        }
        
        /// <remarks/>
        public void executeAreaAlertAsync(AreaName in0, AlertMsg in1, WhiteLists in2, AdditionalSubscribers in3, System.Nullable<ExecuteMode> in4, object userState) {
            if ((this.executeAreaAlertOperationCompleted == null)) {
                this.executeAreaAlertOperationCompleted = new System.Threading.SendOrPostCallback(this.OnexecuteAreaAlertOperationCompleted);
            }
            this.InvokeAsync("executeAreaAlert", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4}, this.executeAreaAlertOperationCompleted, userState);
        }
        
        private void OnexecuteAreaAlertOperationCompleted(object arg) {
            if ((this.executeAreaAlertCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.executeAreaAlertCompleted(this, new executeAreaAlertCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.domain.common.alertix.cellvision")]
    public partial class AreaName {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://vo.common.alertix.cellvision")]
    public partial class Response {
        
        private int codeField;
        
        private bool codeFieldSpecified;
        
        private string messageField;
        
        private bool successfulField;
        
        private bool successfulFieldSpecified;
        
        /// <remarks/>
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codeSpecified {
            get {
                return this.codeFieldSpecified;
            }
            set {
                this.codeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public bool successful {
            get {
                return this.successfulField;
            }
            set {
                this.successfulField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool successfulSpecified {
            get {
                return this.successfulFieldSpecified;
            }
            set {
                this.successfulFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.domain.common.alertix.cellvision")]
    public partial class Point {
        
        private double xField;
        
        private bool xFieldSpecified;
        
        private double yField;
        
        private bool yFieldSpecified;
        
        /// <remarks/>
        public double x {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool xSpecified {
            get {
                return this.xFieldSpecified;
            }
            set {
                this.xFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ySpecified {
            get {
                return this.yFieldSpecified;
            }
            set {
                this.yFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.domain.common.alertix.cellvision")]
    public partial class Polygon {
        
        private Point[] verticesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Point[] vertices {
            get {
                return this.verticesField;
            }
            set {
                this.verticesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.domain.common.alertix.cellvision")]
    public partial class JobId {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://vo.api.alertix.cellvision")]
    public partial class AlertResponse {
        
        private int codeField;
        
        private bool codeFieldSpecified;
        
        private JobId jobIdField;
        
        private string messageField;
        
        private bool successfulField;
        
        private bool successfulFieldSpecified;
        
        /// <remarks/>
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codeSpecified {
            get {
                return this.codeFieldSpecified;
            }
            set {
                this.codeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public JobId jobId {
            get {
                return this.jobIdField;
            }
            set {
                this.jobIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public bool successful {
            get {
                return this.successfulField;
            }
            set {
                this.successfulField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool successfulSpecified {
            get {
                return this.successfulFieldSpecified;
            }
            set {
                this.successfulFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.domain.common.alertix.cellvision")]
    public partial class Msisdn {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.domain.common.alertix.cellvision")]
    public partial class AdditionalSubscribers {
        
        private Msisdn[] subscribersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Msisdn[] subscribers {
            get {
                return this.subscribersField;
            }
            set {
                this.subscribersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.domain.common.alertix.cellvision")]
    public partial class WhiteListName {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.domain.common.alertix.cellvision")]
    public partial class WhiteLists {
        
        private WhiteListName[] whiteListsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public WhiteListName[] whiteLists {
            get {
                return this.whiteListsField;
            }
            set {
                this.whiteListsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.domain.common.alertix.cellvision")]
    public partial class TextMessage {
        
        private string oaField;
        
        private string textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string oa {
            get {
                return this.oaField;
            }
            set {
                this.oaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.domain.common.alertix.cellvision")]
    public partial class CountryCode {
        
        private System.Nullable<int> valueField;
        
        private bool valueFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valueSpecified {
            get {
                return this.valueFieldSpecified;
            }
            set {
                this.valueFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.domain.common.alertix.cellvision")]
    public partial class CountryTextMessage {
        
        private CountryCode[] countryCodesField;
        
        private string oaField;
        
        private string textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public CountryCode[] countryCodes {
            get {
                return this.countryCodesField;
            }
            set {
                this.countryCodesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string oa {
            get {
                return this.oaField;
            }
            set {
                this.oaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.domain.common.alertix.cellvision")]
    public partial class AlertMsg {
        
        private CountryTextMessage[] countryMessagesField;
        
        private TextMessage defaultMessageField;
        
        private System.DateTime expiryTimeField;
        
        private bool expiryTimeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public CountryTextMessage[] countryMessages {
            get {
                return this.countryMessagesField;
            }
            set {
                this.countryMessagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public TextMessage defaultMessage {
            get {
                return this.defaultMessageField;
            }
            set {
                this.defaultMessageField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime expiryTime {
            get {
                return this.expiryTimeField;
            }
            set {
                this.expiryTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool expiryTimeSpecified {
            get {
                return this.expiryTimeFieldSpecified;
            }
            set {
                this.expiryTimeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://domain.common.alertix.cellvision")]
    public enum ExecuteMode {
        
        /// <remarks/>
        UNKNOWN,
        
        /// <remarks/>
        LIVE,
        
        /// <remarks/>
        SIMULATE,
        
        /// <remarks/>
        SILENT,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void prepareAreaAlertCompletedEventHandler(object sender, prepareAreaAlertCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class prepareAreaAlertCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal prepareAreaAlertCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AlertResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AlertResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void executeAdditionalAlertCompletedEventHandler(object sender, executeAdditionalAlertCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class executeAdditionalAlertCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal executeAdditionalAlertCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AlertResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AlertResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void prepareCustomAlertCompletedEventHandler(object sender, prepareCustomAlertCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class prepareCustomAlertCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal prepareCustomAlertCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AlertResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AlertResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void executeCustomAlertCompletedEventHandler(object sender, executeCustomAlertCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class executeCustomAlertCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal executeCustomAlertCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AlertResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AlertResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void cancelPreparedAlertCompletedEventHandler(object sender, cancelPreparedAlertCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cancelPreparedAlertCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cancelPreparedAlertCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Response)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void executePreparedAlertCompletedEventHandler(object sender, executePreparedAlertCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class executePreparedAlertCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal executePreparedAlertCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Response)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void executeAreaAlertCompletedEventHandler(object sender, executeAreaAlertCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class executeAreaAlertCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal executeAreaAlertCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AlertResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AlertResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591