//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

//
// This source code was auto-generated by xsd, Version=4.0.30319.1.
//


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class info_msg {

    private string typeField;

    private string sourceField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string source {
        get {
            return this.sourceField;
        }
        set {
            this.sourceField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class road65 {

    private info_type info_typeField;

    private info_msg info_msgField;

    private string error_codeField;

    private string logidField;

    private input inputField;

    private @break breakField;

    private result resultField;

    /// <remarks/>
    public info_type info_type {
        get {
            return this.info_typeField;
        }
        set {
            this.info_typeField = value;
        }
    }

    /// <remarks/>
    public info_msg info_msg {
        get {
            return this.info_msgField;
        }
        set {
            this.info_msgField = value;
        }
    }

    /// <remarks/>
    public string error_code {
        get {
            return this.error_codeField;
        }
        set {
            this.error_codeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string logid {
        get {
            return this.logidField;
        }
        set {
            this.logidField = value;
        }
    }

    /// <remarks/>
    public input input {
        get {
            return this.inputField;
        }
        set {
            this.inputField = value;
        }
    }

    /// <remarks/>
    public @break @break {
        get {
            return this.breakField;
        }
        set {
            this.breakField = value;
        }
    }

    /// <remarks/>
    public result result {
        get {
            return this.resultField;
        }
        set {
            this.resultField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="")]
public enum info_type {

    /// <remarks/>
    ERROR,

    /// <remarks/>
    BREAK,

    /// <remarks/>
    DONE,

    /// <remarks/>
    INCOMPLETE,

    /// <remarks/>
    FAILED,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class input {

    private string countryField;

    private string languageField;

    private string zipcodeField;

    private string cityField;

    private string streetnameField;

    private string house_numberField;

    private string house_number_alfaField;

    private string statusField;

    private string city_lengthField;

    private string street_lengthField;

    private string xslfileField;

    private string interactivField;

    private string aLLTOUPPERField;

    private string request_idField;

    private string moduleField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string language {
        get {
            return this.languageField;
        }
        set {
            this.languageField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string zipcode {
        get {
            return this.zipcodeField;
        }
        set {
            this.zipcodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string city {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string streetname {
        get {
            return this.streetnameField;
        }
        set {
            this.streetnameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string house_number {
        get {
            return this.house_numberField;
        }
        set {
            this.house_numberField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string house_number_alfa {
        get {
            return this.house_number_alfaField;
        }
        set {
            this.house_number_alfaField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
    public string city_length {
        get {
            return this.city_lengthField;
        }
        set {
            this.city_lengthField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
    public string street_length {
        get {
            return this.street_lengthField;
        }
        set {
            this.street_lengthField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string xslfile {
        get {
            return this.xslfileField;
        }
        set {
            this.xslfileField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
    public string interactiv {
        get {
            return this.interactivField;
        }
        set {
            this.interactivField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
    public string ALLTOUPPER {
        get {
            return this.aLLTOUPPERField;
        }
        set {
            this.aLLTOUPPERField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string request_id {
        get {
            return this.request_idField;
        }
        set {
            this.request_idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string module {
        get {
            return this.moduleField;
        }
        set {
            this.moduleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class @break {

    private breakLine[] lineField;

    private breaktype typeField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("line")]
    public breakLine[] line {
        get {
            return this.lineField;
        }
        set {
            this.lineField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public breaktype type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
public partial class breakLine {

    private string idField;

    private string statusField;

    private string zipcodeField;

    private string cityField;

    private string streetnameField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string zipcode {
        get {
            return this.zipcodeField;
        }
        set {
            this.zipcodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string city {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string streetname {
        get {
            return this.streetnameField;
        }
        set {
            this.streetnameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="")]
public enum breaktype {

    /// <remarks/>
    cities,

    /// <remarks/>
    streets,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class result {

    private string countryField;

    private string zipcodeField;

    private string cityField;

    private string streetnameField;

    private string street_idField;

    private string city_idField;

    private string street_statusField;

    private string street_languageField;

    private string city_languageField;

    private string nis5Field;

    private string nis6Field;

    private string nis9Field;

    private string r65_extra1Field;

    private string r65_extra2Field;

    private string r65_extra3Field;

    private string r65_extra4Field;

    private string r65_extra5Field;

    private string aGS_streetnameField;

    private string aGS_city_cdField;

    private string aGS_street_cdField;

    private string aGS_zipcodeField;

    private string aGS_cityField;

    private string aGS_languageField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string zipcode {
        get {
            return this.zipcodeField;
        }
        set {
            this.zipcodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string city {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string streetname {
        get {
            return this.streetnameField;
        }
        set {
            this.streetnameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
    public string street_id {
        get {
            return this.street_idField;
        }
        set {
            this.street_idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
    public string city_id {
        get {
            return this.city_idField;
        }
        set {
            this.city_idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string street_status {
        get {
            return this.street_statusField;
        }
        set {
            this.street_statusField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string street_language {
        get {
            return this.street_languageField;
        }
        set {
            this.street_languageField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string city_language {
        get {
            return this.city_languageField;
        }
        set {
            this.city_languageField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string nis5 {
        get {
            return this.nis5Field;
        }
        set {
            this.nis5Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string nis6 {
        get {
            return this.nis6Field;
        }
        set {
            this.nis6Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string nis9 {
        get {
            return this.nis9Field;
        }
        set {
            this.nis9Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string r65_extra1 {
        get {
            return this.r65_extra1Field;
        }
        set {
            this.r65_extra1Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string r65_extra2 {
        get {
            return this.r65_extra2Field;
        }
        set {
            this.r65_extra2Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string r65_extra3 {
        get {
            return this.r65_extra3Field;
        }
        set {
            this.r65_extra3Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string r65_extra4 {
        get {
            return this.r65_extra4Field;
        }
        set {
            this.r65_extra4Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string r65_extra5 {
        get {
            return this.r65_extra5Field;
        }
        set {
            this.r65_extra5Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string AGS_streetname {
        get {
            return this.aGS_streetnameField;
        }
        set {
            this.aGS_streetnameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
    public string AGS_city_cd {
        get {
            return this.aGS_city_cdField;
        }
        set {
            this.aGS_city_cdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
    public string AGS_street_cd {
        get {
            return this.aGS_street_cdField;
        }
        set {
            this.aGS_street_cdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
    public string AGS_zipcode {
        get {
            return this.aGS_zipcodeField;
        }
        set {
            this.aGS_zipcodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string AGS_city {
        get {
            return this.aGS_cityField;
        }
        set {
            this.aGS_cityField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string AGS_language {
        get {
            return this.aGS_languageField;
        }
        set {
            this.aGS_languageField = value;
        }
    }
}
