//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.1433.
// 
#pragma warning disable 1591

namespace UMSAlertiX.AlertiXStatusApi {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="StatusApiHttpBinding", Namespace="http://webservice.api.alertix.jpipe.cellvision")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(JobInfo[]))]
    public partial class StatusApi : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getAllJobsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getJobStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback getAlertStatusByCountryCodeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public StatusApi() {
            this.Url = global::UMSAlertiX.Properties.Settings.Default.UMSAlertiX_AlertiXStatusApi_StatusApi;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }

        protected override System.Net.WebRequest GetWebRequest(Uri uri)
        {
            System.Net.HttpWebRequest req;
            req = (System.Net.HttpWebRequest)base.GetWebRequest(uri);
            req.KeepAlive = false;
            req.ProtocolVersion = System.Net.HttpVersion.Version10;
            return req;
        }
        
        /// <remarks/>
        public event getAllJobsCompletedEventHandler getAllJobsCompleted;
        
        /// <remarks/>
        public event getJobStatusCompletedEventHandler getJobStatusCompleted;
        
        /// <remarks/>
        public event getAlertStatusByCountryCodeCompletedEventHandler getAlertStatusByCountryCodeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.api.alertix.jpipe.cellvision", ResponseNamespace="http://webservice.api.alertix.jpipe.cellvision", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public AllJobsResponse getAllJobs() {
            object[] results = this.Invoke("getAllJobs", new object[0]);
            return ((AllJobsResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getAllJobsAsync() {
            this.getAllJobsAsync(null);
        }
        
        /// <remarks/>
        public void getAllJobsAsync(object userState) {
            if ((this.getAllJobsOperationCompleted == null)) {
                this.getAllJobsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAllJobsOperationCompleted);
            }
            this.InvokeAsync("getAllJobs", new object[0], this.getAllJobsOperationCompleted, userState);
        }
        
        private void OngetAllJobsOperationCompleted(object arg) {
            if ((this.getAllJobsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAllJobsCompleted(this, new getAllJobsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.api.alertix.jpipe.cellvision", ResponseNamespace="http://webservice.api.alertix.jpipe.cellvision", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public JobStatusResponse getJobStatus([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] JobId in0) {
            object[] results = this.Invoke("getJobStatus", new object[] {
                        in0});
            return ((JobStatusResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getJobStatusAsync(JobId in0) {
            this.getJobStatusAsync(in0, null);
        }
        
        /// <remarks/>
        public void getJobStatusAsync(JobId in0, object userState) {
            if ((this.getJobStatusOperationCompleted == null)) {
                this.getJobStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetJobStatusOperationCompleted);
            }
            this.InvokeAsync("getJobStatus", new object[] {
                        in0}, this.getJobStatusOperationCompleted, userState);
        }
        
        private void OngetJobStatusOperationCompleted(object arg) {
            if ((this.getJobStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getJobStatusCompleted(this, new getJobStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.api.alertix.jpipe.cellvision", ResponseNamespace="http://webservice.api.alertix.jpipe.cellvision", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public CountryCodeAlertStatusResponse getAlertStatusByCountryCode([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] JobId in0) {
            object[] results = this.Invoke("getAlertStatusByCountryCode", new object[] {
                        in0});
            return ((CountryCodeAlertStatusResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getAlertStatusByCountryCodeAsync(JobId in0) {
            this.getAlertStatusByCountryCodeAsync(in0, null);
        }
        
        /// <remarks/>
        public void getAlertStatusByCountryCodeAsync(JobId in0, object userState) {
            if ((this.getAlertStatusByCountryCodeOperationCompleted == null)) {
                this.getAlertStatusByCountryCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAlertStatusByCountryCodeOperationCompleted);
            }
            this.InvokeAsync("getAlertStatusByCountryCode", new object[] {
                        in0}, this.getAlertStatusByCountryCodeOperationCompleted, userState);
        }
        
        private void OngetAlertStatusByCountryCodeOperationCompleted(object arg) {
            if ((this.getAlertStatusByCountryCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAlertStatusByCountryCodeCompleted(this, new getAlertStatusByCountryCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://vo.webservice.api.alertix.jpipe.cellvision")]
    public partial class AllJobsResponse {
        
        private int codeField;
        
        private bool codeFieldSpecified;
        
        private JobInfo[] jobInfosField;
        
        private string messageField;
        
        private bool successfulField;
        
        private bool successfulFieldSpecified;
        
        /// <remarks/>
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codeSpecified {
            get {
                return this.codeFieldSpecified;
            }
            set {
                this.codeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://domain.common.alertix.jpipe.cellvision")]
        public JobInfo[] jobInfos {
            get {
                return this.jobInfosField;
            }
            set {
                this.jobInfosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public bool successful {
            get {
                return this.successfulField;
            }
            set {
                this.successfulField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool successfulSpecified {
            get {
                return this.successfulFieldSpecified;
            }
            set {
                this.successfulFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://domain.common.alertix.jpipe.cellvision")]
    public partial class JobInfo {
        
        private AreaName areaNameField;
        
        private System.Nullable<ExecuteMode> executeModeField;
        
        private bool executeModeFieldSpecified;
        
        private UserId executorField;
        
        private System.DateTime expiryField;
        
        private bool expiryFieldSpecified;
        
        private JobId jobIdField;
        
        private System.Nullable<JobStatus> jobStatusField;
        
        private bool jobStatusFieldSpecified;
        
        private System.DateTime startedField;
        
        private bool startedFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public AreaName areaName {
            get {
                return this.areaNameField;
            }
            set {
                this.areaNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<ExecuteMode> executeMode {
            get {
                return this.executeModeField;
            }
            set {
                this.executeModeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool executeModeSpecified {
            get {
                return this.executeModeFieldSpecified;
            }
            set {
                this.executeModeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public UserId executor {
            get {
                return this.executorField;
            }
            set {
                this.executorField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime expiry {
            get {
                return this.expiryField;
            }
            set {
                this.expiryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool expirySpecified {
            get {
                return this.expiryFieldSpecified;
            }
            set {
                this.expiryFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public JobId jobId {
            get {
                return this.jobIdField;
            }
            set {
                this.jobIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<JobStatus> jobStatus {
            get {
                return this.jobStatusField;
            }
            set {
                this.jobStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool jobStatusSpecified {
            get {
                return this.jobStatusFieldSpecified;
            }
            set {
                this.jobStatusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime started {
            get {
                return this.startedField;
            }
            set {
                this.startedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startedSpecified {
            get {
                return this.startedFieldSpecified;
            }
            set {
                this.startedFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://domain.common.alertix.jpipe.cellvision")]
    public partial class AreaName {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://domain.common.alertix.jpipe.cellvision")]
    public partial class JobId {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://domain.common.alertix.jpipe.cellvision")]
    public partial class CountryCodeAlertStatus {
        
        private int countryCodeField;
        
        private bool countryCodeFieldSpecified;
        
        private int deliveredSuccessfullyField;
        
        private bool deliveredSuccessfullyFieldSpecified;
        
        private int deliveryExpiredField;
        
        private bool deliveryExpiredFieldSpecified;
        
        private int deliveryFailedField;
        
        private bool deliveryFailedFieldSpecified;
        
        private int deliveryUnknownField;
        
        private bool deliveryUnknownFieldSpecified;
        
        private int initializedField;
        
        private bool initializedFieldSpecified;
        
        private int queuedField;
        
        private bool queuedFieldSpecified;
        
        private int submissionFailedField;
        
        private bool submissionFailedFieldSpecified;
        
        private int submittedField;
        
        private bool submittedFieldSpecified;
        
        private int subscribersCountField;
        
        private bool subscribersCountFieldSpecified;
        
        /// <remarks/>
        public int countryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool countryCodeSpecified {
            get {
                return this.countryCodeFieldSpecified;
            }
            set {
                this.countryCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int deliveredSuccessfully {
            get {
                return this.deliveredSuccessfullyField;
            }
            set {
                this.deliveredSuccessfullyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool deliveredSuccessfullySpecified {
            get {
                return this.deliveredSuccessfullyFieldSpecified;
            }
            set {
                this.deliveredSuccessfullyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int deliveryExpired {
            get {
                return this.deliveryExpiredField;
            }
            set {
                this.deliveryExpiredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool deliveryExpiredSpecified {
            get {
                return this.deliveryExpiredFieldSpecified;
            }
            set {
                this.deliveryExpiredFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int deliveryFailed {
            get {
                return this.deliveryFailedField;
            }
            set {
                this.deliveryFailedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool deliveryFailedSpecified {
            get {
                return this.deliveryFailedFieldSpecified;
            }
            set {
                this.deliveryFailedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int deliveryUnknown {
            get {
                return this.deliveryUnknownField;
            }
            set {
                this.deliveryUnknownField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool deliveryUnknownSpecified {
            get {
                return this.deliveryUnknownFieldSpecified;
            }
            set {
                this.deliveryUnknownFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int initialized {
            get {
                return this.initializedField;
            }
            set {
                this.initializedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool initializedSpecified {
            get {
                return this.initializedFieldSpecified;
            }
            set {
                this.initializedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int queued {
            get {
                return this.queuedField;
            }
            set {
                this.queuedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool queuedSpecified {
            get {
                return this.queuedFieldSpecified;
            }
            set {
                this.queuedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int submissionFailed {
            get {
                return this.submissionFailedField;
            }
            set {
                this.submissionFailedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool submissionFailedSpecified {
            get {
                return this.submissionFailedFieldSpecified;
            }
            set {
                this.submissionFailedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int submitted {
            get {
                return this.submittedField;
            }
            set {
                this.submittedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool submittedSpecified {
            get {
                return this.submittedFieldSpecified;
            }
            set {
                this.submittedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int subscribersCount {
            get {
                return this.subscribersCountField;
            }
            set {
                this.subscribersCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool subscribersCountSpecified {
            get {
                return this.subscribersCountFieldSpecified;
            }
            set {
                this.subscribersCountFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://vo.webservice.api.alertix.jpipe.cellvision")]
    public partial class CountryCodeAlertStatusResponse {
        
        private int codeField;
        
        private bool codeFieldSpecified;
        
        private CountryCodeAlertStatus[] countryStatusCountsField;
        
        private string messageField;
        
        private bool successfulField;
        
        private bool successfulFieldSpecified;
        
        /// <remarks/>
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codeSpecified {
            get {
                return this.codeFieldSpecified;
            }
            set {
                this.codeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://domain.common.alertix.jpipe.cellvision")]
        public CountryCodeAlertStatus[] countryStatusCounts {
            get {
                return this.countryStatusCountsField;
            }
            set {
                this.countryStatusCountsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public bool successful {
            get {
                return this.successfulField;
            }
            set {
                this.successfulField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool successfulSpecified {
            get {
                return this.successfulFieldSpecified;
            }
            set {
                this.successfulFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://vo.webservice.api.alertix.jpipe.cellvision")]
    public partial class JobStatusResponse {
        
        private int codeField;
        
        private bool codeFieldSpecified;
        
        private System.Nullable<JobStatus> jobStatusField;
        
        private bool jobStatusFieldSpecified;
        
        private string messageField;
        
        private bool successfulField;
        
        private bool successfulFieldSpecified;
        
        /// <remarks/>
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codeSpecified {
            get {
                return this.codeFieldSpecified;
            }
            set {
                this.codeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<JobStatus> jobStatus {
            get {
                return this.jobStatusField;
            }
            set {
                this.jobStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool jobStatusSpecified {
            get {
                return this.jobStatusFieldSpecified;
            }
            set {
                this.jobStatusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public bool successful {
            get {
                return this.successfulField;
            }
            set {
                this.successfulField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool successfulSpecified {
            get {
                return this.successfulFieldSpecified;
            }
            set {
                this.successfulFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://domain.common.alertix.jpipe.cellvision")]
    public enum JobStatus {
        
        /// <remarks/>
        PREPARING,
        
        /// <remarks/>
        PROCESSING_SUBSCRIBERS,
        
        /// <remarks/>
        NO_SUBSCRIBERS,
        
        /// <remarks/>
        PREPARED,
        
        /// <remarks/>
        PREPARED_LOCK,
        
        /// <remarks/>
        SUBMITTING,
        
        /// <remarks/>
        ERROR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://domain.common.alertix.jpipe.cellvision")]
    public partial class UserId {
        
        private object valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public object value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://domain.common.alertix.jpipe.cellvision")]
    public enum ExecuteMode {
        
        /// <remarks/>
        UNKNOWN,
        
        /// <remarks/>
        LIVE,
        
        /// <remarks/>
        SIMULATE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void getAllJobsCompletedEventHandler(object sender, getAllJobsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getAllJobsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAllJobsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AllJobsResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AllJobsResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void getJobStatusCompletedEventHandler(object sender, getJobStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getJobStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getJobStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public JobStatusResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((JobStatusResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void getAlertStatusByCountryCodeCompletedEventHandler(object sender, getAlertStatusByCountryCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getAlertStatusByCountryCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAlertStatusByCountryCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CountryCodeAlertStatusResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CountryCodeAlertStatusResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591