
package no.ums.ws.parm.admin;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ParmAdmin", targetNamespace = "http://ums.no/ws/parm/admin/", wsdlLocation = "http://localhost/ws/ParmAdmin.asmx?WSDL")
public class ParmAdmin
    extends Service
{

    private final static URL PARMADMIN_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost/ws/ParmAdmin.asmx?WSDL");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        PARMADMIN_WSDL_LOCATION = url;
    }

    public ParmAdmin(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ParmAdmin() {
        super(PARMADMIN_WSDL_LOCATION, new QName("http://ums.no/ws/parm/admin/", "ParmAdmin"));
    }

    /**
     * 
     * @return
     *     returns ParmAdminSoap
     */
    @WebEndpoint(name = "ParmAdminSoap")
    public ParmAdminSoap getParmAdminSoap() {
        return (ParmAdminSoap)super.getPort(new QName("http://ums.no/ws/parm/admin/", "ParmAdminSoap"), ParmAdminSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ParmAdminSoap
     */
    @WebEndpoint(name = "ParmAdminSoap")
    public ParmAdminSoap getParmAdminSoap(WebServiceFeature... features) {
        return (ParmAdminSoap)super.getPort(new QName("http://ums.no/ws/parm/admin/", "ParmAdminSoap"), ParmAdminSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns ParmAdminSoap
     */
    @WebEndpoint(name = "ParmAdminSoap12")
    public ParmAdminSoap getParmAdminSoap12() {
        return (ParmAdminSoap)super.getPort(new QName("http://ums.no/ws/parm/admin/", "ParmAdminSoap12"), ParmAdminSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ParmAdminSoap
     */
    @WebEndpoint(name = "ParmAdminSoap12")
    public ParmAdminSoap getParmAdminSoap12(WebServiceFeature... features) {
        return (ParmAdminSoap)super.getPort(new QName("http://ums.no/ws/parm/admin/", "ParmAdminSoap12"), ParmAdminSoap.class, features);
    }

}
