
package no.ums.ws.parm.admin;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ParmAdminSoap", targetNamespace = "http://ums.no/ws/parm/admin/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ParmAdminSoap {


    /**
     * 
     * @param ev
     * @param logon
     * @return
     *     returns no.ums.ws.parm.admin.UPAEVENTRESULT
     */
    @WebMethod(operationName = "ExecEventUpdate", action = "http://ums.no/ws/parm/admin/ExecEventUpdate")
    @WebResult(name = "ExecEventUpdateResult", targetNamespace = "http://ums.no/ws/parm/admin/")
    @RequestWrapper(localName = "ExecEventUpdate", targetNamespace = "http://ums.no/ws/parm/admin/", className = "no.ums.ws.parm.admin.ExecEventUpdate")
    @ResponseWrapper(localName = "ExecEventUpdateResponse", targetNamespace = "http://ums.no/ws/parm/admin/", className = "no.ums.ws.parm.admin.ExecEventUpdateResponse")
    public UPAEVENTRESULT execEventUpdate(
        @WebParam(name = "logon", targetNamespace = "http://ums.no/ws/parm/admin/")
        ULOGONINFO logon,
        @WebParam(name = "ev", targetNamespace = "http://ums.no/ws/parm/admin/")
        PAEVENT ev);

    /**
     * 
     * @param obj
     * @param logon
     * @return
     *     returns no.ums.ws.parm.admin.UPAOBJECTRESULT
     */
    @WebMethod(operationName = "ExecObjectUpdate", action = "http://ums.no/ws/parm/admin/ExecObjectUpdate")
    @WebResult(name = "ExecObjectUpdateResult", targetNamespace = "http://ums.no/ws/parm/admin/")
    @RequestWrapper(localName = "ExecObjectUpdate", targetNamespace = "http://ums.no/ws/parm/admin/", className = "no.ums.ws.parm.admin.ExecObjectUpdate")
    @ResponseWrapper(localName = "ExecObjectUpdateResponse", targetNamespace = "http://ums.no/ws/parm/admin/", className = "no.ums.ws.parm.admin.ExecObjectUpdateResponse")
    public UPAOBJECTRESULT execObjectUpdate(
        @WebParam(name = "logon", targetNamespace = "http://ums.no/ws/parm/admin/")
        ULOGONINFO logon,
        @WebParam(name = "obj", targetNamespace = "http://ums.no/ws/parm/admin/")
        PAOBJECT obj);

    /**
     * 
     * @param obj
     * @param logon
     * @param type
     * @return
     *     returns no.ums.ws.parm.admin.UPAOBJECTRESULT
     */
    @WebMethod(operationName = "ExecPAShapeUpdate", action = "http://ums.no/ws/parm/admin/ExecPAShapeUpdate")
    @WebResult(name = "ExecPAShapeUpdateResult", targetNamespace = "http://ums.no/ws/parm/admin/")
    @RequestWrapper(localName = "ExecPAShapeUpdate", targetNamespace = "http://ums.no/ws/parm/admin/", className = "no.ums.ws.parm.admin.ExecPAShapeUpdate")
    @ResponseWrapper(localName = "ExecPAShapeUpdateResponse", targetNamespace = "http://ums.no/ws/parm/admin/", className = "no.ums.ws.parm.admin.ExecPAShapeUpdateResponse")
    public UPAOBJECTRESULT execPAShapeUpdate(
        @WebParam(name = "logon", targetNamespace = "http://ums.no/ws/parm/admin/")
        ULOGONINFO logon,
        @WebParam(name = "obj", targetNamespace = "http://ums.no/ws/parm/admin/")
        PAOBJECT obj,
        @WebParam(name = "type", targetNamespace = "http://ums.no/ws/parm/admin/")
        PASHAPETYPES type);

    /**
     * 
     * @param e
     * @param s
     * @param p
     * @param l
     * @return
     *     returns int
     */
    @WebMethod(operationName = "Defines", action = "http://ums.no/ws/parm/admin/Defines")
    @WebResult(name = "DefinesResult", targetNamespace = "http://ums.no/ws/parm/admin/")
    @RequestWrapper(localName = "Defines", targetNamespace = "http://ums.no/ws/parm/admin/", className = "no.ums.ws.parm.admin.Defines")
    @ResponseWrapper(localName = "DefinesResponse", targetNamespace = "http://ums.no/ws/parm/admin/", className = "no.ums.ws.parm.admin.DefinesResponse")
    public int defines(
        @WebParam(name = "e", targetNamespace = "http://ums.no/ws/parm/admin/")
        UEllipse e,
        @WebParam(name = "p", targetNamespace = "http://ums.no/ws/parm/admin/")
        UPolygon p,
        @WebParam(name = "s", targetNamespace = "http://ums.no/ws/parm/admin/")
        UGeminiStreet s,
        @WebParam(name = "l", targetNamespace = "http://ums.no/ws/parm/admin/")
        ULocationBasedAlert l);

    /**
     * 
     * @param a
     * @param logon
     * @return
     *     returns no.ums.ws.parm.admin.UPAALERTRESTULT
     */
    @WebMethod(operationName = "ExecAlertUpdate", action = "http://ums.no/ws/parm/admin/ExecAlertUpdate")
    @WebResult(name = "ExecAlertUpdateResult", targetNamespace = "http://ums.no/ws/parm/admin/")
    @RequestWrapper(localName = "ExecAlertUpdate", targetNamespace = "http://ums.no/ws/parm/admin/", className = "no.ums.ws.parm.admin.ExecAlertUpdate")
    @ResponseWrapper(localName = "ExecAlertUpdateResponse", targetNamespace = "http://ums.no/ws/parm/admin/", className = "no.ums.ws.parm.admin.ExecAlertUpdateResponse")
    public UPAALERTRESTULT execAlertUpdate(
        @WebParam(name = "logon", targetNamespace = "http://ums.no/ws/parm/admin/")
        ULOGONINFO logon,
        @WebParam(name = "a", targetNamespace = "http://ums.no/ws/parm/admin/")
        PAALERT a);

    /**
     * 
     * @param szPolyfilename
     * @param logoninfo
     * @param szFilename
     * @param zipfile
     * @return
     *     returns byte[]
     */
    @WebMethod(operationName = "UpdateParm", action = "http://ums.no/ws/parm/admin/UpdateParm")
    @WebResult(name = "UpdateParmResult", targetNamespace = "http://ums.no/ws/parm/admin/")
    @RequestWrapper(localName = "UpdateParm", targetNamespace = "http://ums.no/ws/parm/admin/", className = "no.ums.ws.parm.admin.UpdateParm")
    @ResponseWrapper(localName = "UpdateParmResponse", targetNamespace = "http://ums.no/ws/parm/admin/", className = "no.ums.ws.parm.admin.UpdateParmResponse")
    public byte[] updateParm(
        @WebParam(name = "zipfile", targetNamespace = "http://ums.no/ws/parm/admin/")
        byte[] zipfile,
        @WebParam(name = "logoninfo", targetNamespace = "http://ums.no/ws/parm/admin/")
        ULOGONINFO logoninfo,
        @WebParam(name = "sz_filename", targetNamespace = "http://ums.no/ws/parm/admin/")
        String szFilename,
        @WebParam(name = "sz_polyfilename", targetNamespace = "http://ums.no/ws/parm/admin/")
        String szPolyfilename);

    /**
     * 
     * @return
     *     returns no.ums.ws.parm.admin.ArrayOfPAOBJECT
     */
    @WebMethod(operationName = "GetRegions", action = "http://ums.no/ws/parm/admin/GetRegions")
    @WebResult(name = "GetRegionsResult", targetNamespace = "http://ums.no/ws/parm/admin/")
    @RequestWrapper(localName = "GetRegions", targetNamespace = "http://ums.no/ws/parm/admin/", className = "no.ums.ws.parm.admin.GetRegions")
    @ResponseWrapper(localName = "GetRegionsResponse", targetNamespace = "http://ums.no/ws/parm/admin/", className = "no.ums.ws.parm.admin.GetRegionsResponse")
    public ArrayOfPAOBJECT getRegions();

}
