/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LogRecordDetail.java
 *
 * Created on Jan 27, 2011, 1:59:42 PM
 */

package no.ums.log.swing;

import java.awt.Color;
import java.awt.EventQueue;
import java.io.PrintWriter;
import java.io.StringWriter;
import java.util.logging.Level;
import java.util.logging.LogRecord;
import javax.annotation.Nullable;
import javax.swing.JFrame;

/**
 *
 * @author staaleu
 */
public class LogRecordDetail extends javax.swing.JPanel {

    /** Creates new form LogRecordDetail */
    public LogRecordDetail() {
        initComponents();
        setLogRecord(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        javax.swing.JLabel time = new javax.swing.JLabel();
        javax.swing.JLabel levelLabel = new javax.swing.JLabel();
        javax.swing.JLabel sourceLabel = new javax.swing.JLabel();
        javax.swing.JLabel messageLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        messageValue = new javax.swing.JTextArea();
        sourceValue = new javax.swing.JLabel();
        levelValue = new javax.swing.JLabel();
        timeValue = new javax.swing.JLabel();
        exceptionPanel = new javax.swing.JPanel();
        javax.swing.JLabel exceptionLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        exceptionValue = new javax.swing.JTextArea();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setPreferredSize(new java.awt.Dimension(250, 300));
        setRequestFocusEnabled(false);

        time.setText("Time:");

        levelLabel.setText("Level:");

        sourceLabel.setText("Source:");

        messageLabel.setText("Message:");

        messageValue.setColumns(20);
        messageValue.setEditable(false);
        messageValue.setLineWrap(true);
        messageValue.setRows(3);
        messageValue.setTabSize(4);
        jScrollPane2.setViewportView(messageValue);

        sourceValue.setText("jLabel7");

        levelValue.setText("jLabel8");

        timeValue.setText("jLabel9");

        exceptionLabel.setText("Exception:");

        exceptionValue.setColumns(20);
        exceptionValue.setEditable(false);
        exceptionValue.setRows(5);
        jScrollPane3.setViewportView(exceptionValue);

        javax.swing.GroupLayout exceptionPanelLayout = new javax.swing.GroupLayout(exceptionPanel);
        exceptionPanel.setLayout(exceptionPanelLayout);
        exceptionPanelLayout.setHorizontalGroup(
            exceptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exceptionPanelLayout.createSequentialGroup()
                .addComponent(exceptionLabel)
                .addContainerGap(162, Short.MAX_VALUE))
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
        );
        exceptionPanelLayout.setVerticalGroup(
            exceptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exceptionPanelLayout.createSequentialGroup()
                .addComponent(exceptionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(exceptionPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sourceLabel)
                            .addComponent(levelLabel)
                            .addComponent(time))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(timeValue)
                            .addComponent(levelValue)))
                    .addComponent(messageLabel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(sourceValue, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(time)
                    .addComponent(timeValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(levelLabel)
                    .addComponent(levelValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sourceLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sourceValue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(messageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exceptionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel exceptionPanel;
    private javax.swing.JTextArea exceptionValue;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel levelValue;
    private javax.swing.JTextArea messageValue;
    private javax.swing.JLabel sourceValue;
    private javax.swing.JLabel timeValue;
    // End of variables declaration//GEN-END:variables

    public void setLogRecord(@Nullable LogRecord record) {
        exceptionPanel.setVisible(false);
        timeValue.setText("");
        levelValue.setText("");
        sourceValue.setText("");
        messageValue.setText("");
        if (record != null) {
            timeValue.setText(LogSwingUtil.formatTime(record.getMillis()));
            levelValue.setText(record.getLevel().getLocalizedName());
            levelValue.setForeground(LogSwingUtil.toColor(record.getLevel()));
            sourceValue.setText(record.getLoggerName());
            messageValue.setText(record.getMessage());
            if (record.getThrown() != null) {
                exceptionPanel.setVisible(true);
                final StringWriter sw = new StringWriter();
                record.getThrown().printStackTrace(new PrintWriter(sw));
                exceptionValue.setText(sw.toString());
            }
        }
    }

}
