/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LogMessage.java
 *
 * Created on Jan 27, 2011, 10:47:02 AM
 */

package no.ums.log.swing;

import com.google.common.primitives.Ints;
import com.google.common.primitives.Primitives;
import org.joda.time.format.DateTimeFormatter;
import org.joda.time.format.DateTimeFormatterBuilder;

import javax.swing.*;
import java.awt.*;
import java.util.Comparator;
import java.util.NavigableMap;
import java.util.TreeMap;
import java.util.logging.Level;
import java.util.logging.LogRecord;

/**
 * @author staaleu
 */
public class LogRecordLine extends javax.swing.JPanel {



    /**
     * Creates new form LogMessage
     */
    public LogRecordLine(LogRecord logRecord, boolean selected) {
        initComponents();
        level.setForeground(LogSwingUtil.toColor(logRecord.getLevel()));
        level.setText(logRecord.getLevel().getLocalizedName());
        time.setText(LogSwingUtil.formatTime(logRecord.getMillis()));
        msg.setText(logRecord.getMessage());
        if (selected) {
            setBackground(UIManager.getColor("List.selectionBackground"));
        }
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        level = new javax.swing.JLabel();
        msg = new javax.swing.JLabel();
        time = new javax.swing.JLabel();

        level.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        level.setForeground(new java.awt.Color(2, 167, 34));
        level.setText("DEBUG");

        msg.setText("This is the message");

        time.setText("10:48:35");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(time)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(level, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(msg, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(time)
                .addComponent(level)
                .addComponent(msg))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel level;
    private javax.swing.JLabel msg;
    private javax.swing.JLabel time;
    // End of variables declaration//GEN-END:variables

}
