//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.1432.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="ParmAdminSoap", Namespace="http://ums.no/ws/parm/admin/")]
public partial class ParmAdmin : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback GetEventListOperationCompleted;
    
    private System.Threading.SendOrPostCallback UpdateParmOperationCompleted;
    
    /// <remarks/>
    public ParmAdmin() {
        this.Url = "https://secure.ums2.no/vb4utv/ExecAlert/WS/ParmAdmin.asmx";
    }
    
    /// <remarks/>
    public event GetEventListCompletedEventHandler GetEventListCompleted;
    
    /// <remarks/>
    public event UpdateParmCompletedEventHandler UpdateParmCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ums.no/ws/parm/admin/GetEventList", RequestNamespace="http://ums.no/ws/parm/admin/", ResponseNamespace="http://ums.no/ws/parm/admin/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public PAEVENT[] GetEventList(ULOGONINFO logoninfo) {
        object[] results = this.Invoke("GetEventList", new object[] {
                    logoninfo});
        return ((PAEVENT[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetEventList(ULOGONINFO logoninfo, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetEventList", new object[] {
                    logoninfo}, callback, asyncState);
    }
    
    /// <remarks/>
    public PAEVENT[] EndGetEventList(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((PAEVENT[])(results[0]));
    }
    
    /// <remarks/>
    public void GetEventListAsync(ULOGONINFO logoninfo) {
        this.GetEventListAsync(logoninfo, null);
    }
    
    /// <remarks/>
    public void GetEventListAsync(ULOGONINFO logoninfo, object userState) {
        if ((this.GetEventListOperationCompleted == null)) {
            this.GetEventListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEventListOperationCompleted);
        }
        this.InvokeAsync("GetEventList", new object[] {
                    logoninfo}, this.GetEventListOperationCompleted, userState);
    }
    
    private void OnGetEventListOperationCompleted(object arg) {
        if ((this.GetEventListCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetEventListCompleted(this, new GetEventListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ums.no/ws/parm/admin/UpdateParm", RequestNamespace="http://ums.no/ws/parm/admin/", ResponseNamespace="http://ums.no/ws/parm/admin/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] UpdateParm([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] zipfile, ULOGONINFO logoninfo, string sz_filename, string sz_polyfilename) {
        object[] results = this.Invoke("UpdateParm", new object[] {
                    zipfile,
                    logoninfo,
                    sz_filename,
                    sz_polyfilename});
        return ((byte[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginUpdateParm(byte[] zipfile, ULOGONINFO logoninfo, string sz_filename, string sz_polyfilename, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("UpdateParm", new object[] {
                    zipfile,
                    logoninfo,
                    sz_filename,
                    sz_polyfilename}, callback, asyncState);
    }
    
    /// <remarks/>
    public byte[] EndUpdateParm(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((byte[])(results[0]));
    }
    
    /// <remarks/>
    public void UpdateParmAsync(byte[] zipfile, ULOGONINFO logoninfo, string sz_filename, string sz_polyfilename) {
        this.UpdateParmAsync(zipfile, logoninfo, sz_filename, sz_polyfilename, null);
    }
    
    /// <remarks/>
    public void UpdateParmAsync(byte[] zipfile, ULOGONINFO logoninfo, string sz_filename, string sz_polyfilename, object userState) {
        if ((this.UpdateParmOperationCompleted == null)) {
            this.UpdateParmOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateParmOperationCompleted);
        }
        this.InvokeAsync("UpdateParm", new object[] {
                    zipfile,
                    logoninfo,
                    sz_filename,
                    sz_polyfilename}, this.UpdateParmOperationCompleted, userState);
    }
    
    private void OnUpdateParmOperationCompleted(object arg) {
        if ((this.UpdateParmCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.UpdateParmCompleted(this, new UpdateParmCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ums.no/ws/parm/admin/")]
public partial class ULOGONINFO {
    
    private long l_userpkField;
    
    private int l_comppkField;
    
    private int l_deptpkField;
    
    private string sz_deptidField;
    
    private string sz_useridField;
    
    private string sz_compidField;
    
    private string sz_passwordField;
    
    private int l_deptpriField;
    
    private int l_priserverField;
    
    private int l_altserversField;
    
    private string sz_stdccField;
    
    /// <remarks/>
    public long l_userpk {
        get {
            return this.l_userpkField;
        }
        set {
            this.l_userpkField = value;
        }
    }
    
    /// <remarks/>
    public int l_comppk {
        get {
            return this.l_comppkField;
        }
        set {
            this.l_comppkField = value;
        }
    }
    
    /// <remarks/>
    public int l_deptpk {
        get {
            return this.l_deptpkField;
        }
        set {
            this.l_deptpkField = value;
        }
    }
    
    /// <remarks/>
    public string sz_deptid {
        get {
            return this.sz_deptidField;
        }
        set {
            this.sz_deptidField = value;
        }
    }
    
    /// <remarks/>
    public string sz_userid {
        get {
            return this.sz_useridField;
        }
        set {
            this.sz_useridField = value;
        }
    }
    
    /// <remarks/>
    public string sz_compid {
        get {
            return this.sz_compidField;
        }
        set {
            this.sz_compidField = value;
        }
    }
    
    /// <remarks/>
    public string sz_password {
        get {
            return this.sz_passwordField;
        }
        set {
            this.sz_passwordField = value;
        }
    }
    
    /// <remarks/>
    public int l_deptpri {
        get {
            return this.l_deptpriField;
        }
        set {
            this.l_deptpriField = value;
        }
    }
    
    /// <remarks/>
    public int l_priserver {
        get {
            return this.l_priserverField;
        }
        set {
            this.l_priserverField = value;
        }
    }
    
    /// <remarks/>
    public int l_altservers {
        get {
            return this.l_altserversField;
        }
        set {
            this.l_altserversField = value;
        }
    }
    
    /// <remarks/>
    public string sz_stdcc {
        get {
            return this.sz_stdccField;
        }
        set {
            this.sz_stdccField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ums.no/ws/parm/admin/")]
public abstract partial class UShape {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ums.no/ws/parm/admin/")]
public partial class PAALERT {
    
    private long l_alertpkField;
    
    private string l_parentField;
    
    private string sz_nameField;
    
    private string sz_descriptionField;
    
    private long l_profilepkField;
    
    private string l_schedpkField;
    
    private string sz_oadcField;
    
    private long l_validityField;
    
    private long l_addresstypesField;
    
    private string l_timestampField;
    
    private long f_lockedField;
    
    private string sz_areaidField;
    
    private int n_functionField;
    
    private UShape m_shapeField;
    
    private UShape m_lba_shapeField;
    
    private int n_sendingtypeField;
    
    private int n_maxchannelsField;
    
    private int n_requesttypeField;
    
    private string sz_sms_oadcField;
    
    private string sz_sms_messageField;
    
    /// <remarks/>
    public long l_alertpk {
        get {
            return this.l_alertpkField;
        }
        set {
            this.l_alertpkField = value;
        }
    }
    
    /// <remarks/>
    public string l_parent {
        get {
            return this.l_parentField;
        }
        set {
            this.l_parentField = value;
        }
    }
    
    /// <remarks/>
    public string sz_name {
        get {
            return this.sz_nameField;
        }
        set {
            this.sz_nameField = value;
        }
    }
    
    /// <remarks/>
    public string sz_description {
        get {
            return this.sz_descriptionField;
        }
        set {
            this.sz_descriptionField = value;
        }
    }
    
    /// <remarks/>
    public long l_profilepk {
        get {
            return this.l_profilepkField;
        }
        set {
            this.l_profilepkField = value;
        }
    }
    
    /// <remarks/>
    public string l_schedpk {
        get {
            return this.l_schedpkField;
        }
        set {
            this.l_schedpkField = value;
        }
    }
    
    /// <remarks/>
    public string sz_oadc {
        get {
            return this.sz_oadcField;
        }
        set {
            this.sz_oadcField = value;
        }
    }
    
    /// <remarks/>
    public long l_validity {
        get {
            return this.l_validityField;
        }
        set {
            this.l_validityField = value;
        }
    }
    
    /// <remarks/>
    public long l_addresstypes {
        get {
            return this.l_addresstypesField;
        }
        set {
            this.l_addresstypesField = value;
        }
    }
    
    /// <remarks/>
    public string l_timestamp {
        get {
            return this.l_timestampField;
        }
        set {
            this.l_timestampField = value;
        }
    }
    
    /// <remarks/>
    public long f_locked {
        get {
            return this.f_lockedField;
        }
        set {
            this.f_lockedField = value;
        }
    }
    
    /// <remarks/>
    public string sz_areaid {
        get {
            return this.sz_areaidField;
        }
        set {
            this.sz_areaidField = value;
        }
    }
    
    /// <remarks/>
    public int n_function {
        get {
            return this.n_functionField;
        }
        set {
            this.n_functionField = value;
        }
    }
    
    /// <remarks/>
    public UShape m_shape {
        get {
            return this.m_shapeField;
        }
        set {
            this.m_shapeField = value;
        }
    }
    
    /// <remarks/>
    public UShape m_lba_shape {
        get {
            return this.m_lba_shapeField;
        }
        set {
            this.m_lba_shapeField = value;
        }
    }
    
    /// <remarks/>
    public int n_sendingtype {
        get {
            return this.n_sendingtypeField;
        }
        set {
            this.n_sendingtypeField = value;
        }
    }
    
    /// <remarks/>
    public int n_maxchannels {
        get {
            return this.n_maxchannelsField;
        }
        set {
            this.n_maxchannelsField = value;
        }
    }
    
    /// <remarks/>
    public int n_requesttype {
        get {
            return this.n_requesttypeField;
        }
        set {
            this.n_requesttypeField = value;
        }
    }
    
    /// <remarks/>
    public string sz_sms_oadc {
        get {
            return this.sz_sms_oadcField;
        }
        set {
            this.sz_sms_oadcField = value;
        }
    }
    
    /// <remarks/>
    public string sz_sms_message {
        get {
            return this.sz_sms_messageField;
        }
        set {
            this.sz_sms_messageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ums.no/ws/parm/admin/")]
public partial class PAEVENT {
    
    private long l_eventpkField;
    
    private long l_parentField;
    
    private string sz_nameField;
    
    private string sz_descriptionField;
    
    private long l_categorypkField;
    
    private long l_timestampField;
    
    private float f_epi_lonField;
    
    private float f_epi_latField;
    
    private PAALERT[] alertsField;
    
    /// <remarks/>
    public long l_eventpk {
        get {
            return this.l_eventpkField;
        }
        set {
            this.l_eventpkField = value;
        }
    }
    
    /// <remarks/>
    public long l_parent {
        get {
            return this.l_parentField;
        }
        set {
            this.l_parentField = value;
        }
    }
    
    /// <remarks/>
    public string sz_name {
        get {
            return this.sz_nameField;
        }
        set {
            this.sz_nameField = value;
        }
    }
    
    /// <remarks/>
    public string sz_description {
        get {
            return this.sz_descriptionField;
        }
        set {
            this.sz_descriptionField = value;
        }
    }
    
    /// <remarks/>
    public long l_categorypk {
        get {
            return this.l_categorypkField;
        }
        set {
            this.l_categorypkField = value;
        }
    }
    
    /// <remarks/>
    public long l_timestamp {
        get {
            return this.l_timestampField;
        }
        set {
            this.l_timestampField = value;
        }
    }
    
    /// <remarks/>
    public float f_epi_lon {
        get {
            return this.f_epi_lonField;
        }
        set {
            this.f_epi_lonField = value;
        }
    }
    
    /// <remarks/>
    public float f_epi_lat {
        get {
            return this.f_epi_latField;
        }
        set {
            this.f_epi_latField = value;
        }
    }
    
    /// <remarks/>
    public PAALERT[] alerts {
        get {
            return this.alertsField;
        }
        set {
            this.alertsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void GetEventListCompletedEventHandler(object sender, GetEventListCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetEventListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetEventListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public PAEVENT[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((PAEVENT[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void UpdateParmCompletedEventHandler(object sender, UpdateParmCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class UpdateParmCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal UpdateParmCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public byte[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((byte[])(this.results[0]));
        }
    }
}
